### PR TITLE
Fix commit selection logic to handle intentional rebuilds.

### PR DESCRIPTION
**Pull request by rmmh**
Bug: JENKINS-26290

GitHub Pull Request Builder triggers the Git plugin on changes or by a user comment. 

If a build fails due to a flake, users might request a retest of the same code. This interacts poorly
with logic to avoid rebuilding when polling a repo for changes.

### CODE REVIEW

**Comment by shayoun** [comment]
This PR relevant for https://issues.jenkins-ci.org/browse/JENKINS-26290 and  https://issues.jenkins-ci.org/browse/JENKINS-22537 Jenkins tickets : "stderr: fatal: reference is not a tree:" error.
This reproduced also in our server: we have Gated build that triggered by Github PR and Github poll scm . it fail in about 40% runs. 

Do you know if git/github plugins contains some fix to this issue?

**Comment by MarkEWaite** [comment]
@shayoun I know that **no** git plugin version includes this change.  I generally won't accept changes to this code (used in 130,000+ installations) that does not include tests.

I encourage you to [download the plugin build](https://ci.jenkins.io/job/Plugins/job/git-plugin/job/PR-480/75/artifact/target/git.hpi) for this pull request and test it.  Report your results here.  That helps the author of the pull request see that others are interested, and helps me see that the change has been verified by at least one user.

**Comment by michael-mohemian** [comment]
I think we are affected as well by this issue.

@MarkEWaite Is a "manual" test like you described enough for this PR to be accepted? We can give it a try.

**Comment by rmmh** [comment]
I don't use the plugin any more (or Jenkins at all), and I'm not going to spend the time to write tests. I used this code for months successful while migrating off. The functionality remains fundamentally broken for PR retests.

The tests for this class are pretty bare bones, maybe someone else can extend them?  https://github.com/jenkinsci/git-plugin/blob/master/src/test/java/hudson/plugins/git/util/DefaultBuildChooserTest.java

**Comment by drmmr763** [comment]
I believe I am having this issue and I plan to try test manually. Is the process to simply do something like this?

```
mv /var/lib/jenkins/plugins/git.jpi old-git.jpi
wget https://ci.jenkins.io/job/Plugins/job/git-plugin/job/PR-480/75/artifact/target/git.hpi
service jenkins restart
```

(is the hpi / jpi important?)

**Comment by shantur** [comment]
Having the same issue as this

**Comment by stuartgrice** [comment]
We also have this issue

**Comment by stephenmuss** [comment]
This happens to us on a pull request branch when pushing to it after a review.

**Comment by MarkEWaite** [comment]
Thanks very much for the interest in this pull request.  I'm interested in the results of Interactive testing.

Interactive testing won't be sufficient, but it is a good start.  I am unwilling to require that I and every future maintainer of the plugin must interactively test this case before releasing every new version of the plugin.

**Comment by feliwir** [comment]
Happens for me on Pull Requests aswell. Please merge!

**Comment by MarkEWaite** [comment]
@feliwir did you use the [pull request build](https://ci.jenkins.io/job/Plugins/job/git-plugin/job/PR-480/88/artifact/org/jenkins-ci/plugins/git/4.0.0-rc1440.349983ab0db5/git-4.0.0-rc1440.349983ab0db5.hpi) to confirm that it solves the problem you're seeing without unexpected side effects?

The pull request includes no tests and the author of the original pull request has stated that he won't write tests.  I won't merge this change without confirmation from users that it solves their specific problem.  I won't merge this change without additional automated tests that show the failure (before the change) and confirm the fix (after the change).

**Comment by feliwir** [comment]
@MarkEWaite i am in a production environment, so i can't really test the patch you've attached. But the output seems to indicate that this is the problem:
```
hudson.plugins.git.GitException: Command "git checkout -f d8b3fcdeb45d468fc0f156653ebdc4c0aff6f3f0" returned status code 128:

stdout: 

stderr: fatal: reference is not a tree: d8b3fcdeb45d468fc0f156653ebdc4c0aff6f3f0


	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2002)

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$800(CliGitAPIImpl.java:72)

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2301)

Caused: hudson.plugins.git.GitException: Could not checkout d8b3fcdeb45d468fc0f156653ebdc4c0aff6f3f0

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2325)

	at jenkins.plugins.git.MergeWithGitSCMExtension.checkout(MergeWithGitSCMExtension.java:146)

	at jenkins.plugins.git.MergeWithGitSCMExtension.decorateRevisionToBuild(MergeWithGitSCMExtension.java:112)

	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1094)

	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1187)

	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)

	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:144)

	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:120)

	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:298)

	at hudson.model.ResourceController.execute(ResourceController.java:97)

	at hudson.model.Executor.run(Executor.java:429)

Finished: FAILURE
```

**Comment by MarkEWaite** [comment]
@feliwir unfortunately, less help from Jenkins users means fewer pull requests reviewed, accepted, and released.

I maintain the Jenkins git plugin nights and weekends.  Those nights and weekends are precious.  I make very specific choices of where I will invest my night and weekend time.

One of the ways I decide where I should invest my effort is by seeing where others invest theirs.  If others can't test and report on a pull request, then I assume it is not as important as pull requests where multiple users have tested and reported their results.

**Pull request closed without merging**
