### PR TITLE
Add Relative Target Directory trait

### PR DESCRIPTION
**Pull request by Elbandi**
This patch add the "Check out to a sub-directory" git additional options

### CODE REVIEW

**Comment by MarkEWaite** [comment]
Thanks for the proposal, but the [git plugin documentation](https://plugins.jenkins.io/git/#checkout-to-a-sub-directory) tells the user that they should not use the checkout to a subdirectory extension.  Adding the trait seems like the wrong direction, since it would allow more use of that extension in the Pipeline instead of less:

> This extension should not be used in Jenkins Pipeline (either declarative or scripted). Jenkins Pipeline already provides standard techniques for checkout to a subdirectory. Use ws and dir in Jenkins Pipeline rather than this extension.

Can you explain in more detail why you believe "checkout to subdirectory" should be added as a trait?

**Comment by MarkEWaite** [comment]
Closing pull request.  Further discussion can continue in the pull request, but I don't expect to be persuaded that this should be part of the plugin when Jesse Glick has recommended against the checkout to subdirectory extension.

**Comment by Elbandi** [comment]
We dont migrated to pipeline workflow jet :(

We store custom debian package source code in repo. We build the deb package with [pbuilder](https://wiki.ubuntu.com/PbuilderHowto). pbuilder need dsc (and tar.gz) files, so the package source code need to pack to dsc/tar. 
So the build process is:

1. checking out the source to a subdirectory (call src)
2. pack the source with dpkg-source into dsc/tar, put this files to workspace root.
3. run pbuilder with dsc file, it puts the builded .deb files to "$workspace/output" directory
4. archive the artifacts from this dir

if we not checkout the source into a subdir, we got a "fileloop": the destination files are in source directory. Thats not good.
So we sould separate everythings into directories, otherwise we got a big chaos :)

**Comment by MarkEWaite** [comment]
If you're not using pipeline, then a new trait won't help you.  Use the existing checkout to subdirectory extension in your Freestyle job to checkout to the directory named 'src'.  When you switch to pipeline, you'll use `dir 'src' { checkout() }` in your pipeline definition so that the checkout will be performed in the subdirectory named 'src'.

**Comment by Elbandi** [comment]
in freestyle project there is option to checkout to subdirectory, but it's a multbranch project, this options is missing there :(
If i add this trait, the option is turn on.

**Comment by MarkEWaite** [comment]
> in freestyle project there is option to checkout to subdirectory, but it's a multbranch project, this options is missing there :(
> If i add this trait, the option is turn on.

Multibranch projects are pipeline projects.  Since they are pipeline projects, you can use the `dir` block to checkout to a subdirectory.

**Pull request closed without merging**
