### PR TITLE
[Fixed JENKINS-44037] Add a new `BuildData` action if PreBuildMerge fails

### PR DESCRIPTION
**Pull request by dalvizu**
This fixes a buggy behavior where BuildData from the previous Run is
used instead, which corrupts build history.

### CODE REVIEW

**Comment by dalvizu** [comment]
The build is failing with findbug errors unrelated to anything I've changed?

**Comment by MarkEWaite** [comment]
Yes, sorry about the findbugs failure.  Merge from master to this branch and you should get the latest change to temporarily disable fail on findbugs warning.  Jenkins 2.46 includes some nice improvements for findbugs, but I've not yet adapted the git plugin for those improvements.

**Comment by dalvizu** [comment]
No problem, merged master and repushed :crossed_fingers:

**Comment by dalvizu** [comment]
Is there a way to retrigger tests? It looked like they timed out after 1h. I can't see a way my tests would introduce such behavior, and they have passed on my local environment repeatedly before I submitted them.

As far as testing done - I've added a unit test, and done some manual and exploratory testing. I've been running this in my production environment (~1844 jobs) for about a week now, as well as a test 
environment with about ~400 jobs, and haven't seen any issues.

**Comment by MarkEWaite** [comment]
One way to restart the build is to close the pull request, then open it again.  Another is to submit an additional commit

**Comment by dalvizu** [comment]
@MarkEWaite are you okay if I merge this?

**Comment by MarkEWaite** [comment]
@dalvizu go ahead.  I haven't included a verification test of pre-build merge in my acceptance test suite yet, but let's go ahead with the merge.

**Pull request merged**
