### PR TITLE
[JENKINS-31393] Git plugin fetches all branches before fetching the specified refspec

### PR DESCRIPTION
**Pull request by timocov**

### CODE REVIEW

**Comment by KostyaSha** [comment]
That was unclear also for me, if it stops fetching everything then huge 👍

**Comment by timocov** [comment]
Any updates?

**Comment by timocov** [comment]
@KostyaSha @MarkEWaite May you give any comment about pull request? Should I fix something to you merge it?

**Comment by MarkEWaite** [comment]
I haven't evaluated the pull request yet.  It will need some time before I can complete the evaluation of the pull request.  It passed my cursory review (small changes, no gratuitous white space changes, includes a test, has reasonable commit messages).

The additional steps I'll take before merging it to the master branch will include
- merge the pull request into a private branch
- run the private branch through my multi-platform, multi-version automated tests
- deploy a build of the plugin to my docker instance with various sample bug jobs
- create at least one Jenkins job in my docker instance that exercises the change
- confirm none of the sample bug jobs in my Docker instance regress with this change

**Comment by timocov** [comment]
Thank you so much!

**Comment by timocov** [comment]
@MarkEWaite Could you tell me what I can do to pass all your steps please?

**Comment by MarkEWaite** [comment]
The pull request passed my interactive verification.  I successfully did the following:

- Create a [JENKINS-31393 verification job](https://github.com/MarkEWaite/docker/blob/lts-with-plugins/ref/jobs/bugs/jobs/JENKINS-31393-refspec-ignored-on-initial-fetch/config.xml) which shows that current code fetches more than the user provided refspec
- Run that job in a docker instance, confirm it shows the issue with current code
- Install a copy of this pull request into that docker instance
- Confirm the test job that was failing now passes
- Confirm none of the sample bug jobs in my Docker instance regress with this change

I still need to review the changes in detail, then should be ready to merge the pull request.

**Pull request merged**
