### PR TITLE
JENKINS-25048: Added filters check for notifyCommit event

### PR DESCRIPTION
**Pull request by pbaranchikov**
Acoording to the source code, the excuded/included paths (and other plugins) are ignored when triggering build from notifyCommit URL for the certain commit (SHA1)

### CODE REVIEW

**Comment by christ66** [comment]
:+1:

**Comment by ndeloof** [comment]
@MarkEWaite LGTM, any other point you'd like reviewed before merge ?

**Comment by ndeloof** [comment]
@pbaranchikov please prefix commit log with `[FIXED JENKINS-25048]` so the Jira issue get automagically closed when PR is merged.

**Comment by MarkEWaite** [comment]
This adds a new API (GitSCM.isRevExcluded) on the 2.2.x branch which won't be available on the master (2.3.x) branch. Are we OK with that divergence in the API, or do we need to then include that same API on the master branch?

Should the new API GitSCM.isRevExcluded be annotated with a CheckForNull annotation? (The javadoc clearly declares the semantics of returning null, so maybe there is not much gain from the findbugs annotation)

**Comment by ndeloof** [comment]
This has to be also fixed in master branch. I indeed would prefer the PR target master and this commit get backported to 2.2.x - anyway, 2.2 should only be a maintenance branch, so only focus on blockers and security fixes, so this change is not eligible.

**Comment by pbaranchikov** [comment]
@MarkEWaite, the whole feature should be ported to master branch not to miss the functionality in the future. I suppose, GitSCM.isRevExcluded should be propagated to master branch too, as a part of it.

**Comment by ndeloof** [comment]
@pbaranchikov can you propose this PR on master branch ?
2.2.x branch do exist for maintenance purpose only

**Comment by pbaranchikov** [comment]
Ok, that'll took some additional time. That was created reasonable time ago, that's why it is targeted on 2.2.x branch.

**Comment by pbaranchikov** [comment]
Closing this pull request as switching to master branch

**Comment by pbaranchikov** [comment]
Please, look at the new pull request #318, which is moving to the master branch

**Pull request closed without merging**
