### PR TITLE
not only push but also save a commit

### PR DESCRIPTION
**Pull request by aderigs**
Given that you have configured your build to change and commit  your sources, you possibly not only want to push the commit but also want to save this build. This patch will do this for you.

### CODE REVIEW

**Comment by MarkEWaite** [comment]
Increasing the size of the BuildData seems like it is the opposite direction of the problems reported by many users due to saving too much BuildData and in too many locations.

Can you explain more about the use case for this change, who it will benefit, and how they will use it?

I won't accept the change without tests.  Can you provide tests which fail before your change, and succeed after your change, as one way of illustrating the use of the change?

I would much prefer if the multiple merges in the pull request were rebased out of the pull request so that I don't need to read through merge changes.

**Comment by aderigs** [comment]
Use case:  We are using the git branching model (http://nvie.com/posts/a-successful-git-branching-model) and want to build all changes on all branches. That's why the branch specifier is left blank in our build configurations. The builds are triggered by the github-plugin. Normally a build changes  and commits the source. A successful build will push the commit. Without this patch the push will be triggered by the github-plugin and will be built again, because the build was not saved. You will have an endless recursive build loop ...

**Comment by MarkEWaite** [comment]
Have you considered using an exclusion filter (from the git plugin options) so that the change from your build job is ignored by later polling?  That's the pattern I've seen used elsewhere when the build job is committing changes to the build.

There are many complaints about the memory and startup penalty which the git plugin creates for retaining build history because it includes so much in BuildData.  Your addition to BuildData seems it will further increase the memory use of the git plugin's maintained history, and will further increase memory use and startup time.

**Comment by MarkEWaite** [comment]
Have you considered changing your use model from a single job building multiple branches to a multi-branch job?  A multi-branch job will create and delete a job per branch, then monitors the changes on those branches.

I had been using a single job to build multiple branches and found it confusing to see the history of a single job when each of the builds could be a different branch.  I was never quite sure if my change had fixed a previous problem, or if it was a different branch.  The multi-branch job plugin makes that much simpler by having a job per branch.

**Comment by aderigs** [comment]
I have considered using an exclusion filter, but that did not work. Using the multi-branch project plugin or the pipeline multibranch plugin may be the better idea. I will give it a try. Thank you.

**Comment by aderigs** [comment]
My use case will be better implemented by using the pipeline multibranch plugin.

Thank you!

**Pull request closed without merging**
