### PR TITLE
JENKINS-56284 Make compute changelog extensible

### PR DESCRIPTION
**Pull request by gmshake**
## [JENKINS-56284](https://issues.jenkins-ci.org/browse/JENKINS-56284) - Make compute changelog extensible

Describe the big picture of your changes here to explain to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, include a link to the issue.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/jenkinsci/git-plugin/blob/master/CONTRIBUTING.md) doc
- [x] I have referenced the Jira issue related to my changes in one or more commit messages
- [ ] I have added tests that verify my changes
- [x] Unit tests pass locally with my changes
- [ ] I have added documentation as necessary
- [ ] No Javadoc warnings were introduced with my changes
- [x] No findbugs warnings were introduced with my changes
- [x] I have interactively tested my changes
- [ ] Any dependent changes have been merged and published in upstream modules (like git-client-plugin)

## Types of changes

What types of changes does your code introduce? _Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Further comments

If this is a relatively large or complex change, start the discussion by explaining why you chose the solution you did and what alternatives you considered.

### CODE REVIEW

**Comment by MarkEWaite** [comment]
Thanks for the pull request! I'm currently focused on the testing and fixing for the release of git client plugin 3.0.0 and git plugin 4.0.0.  It will be several months before I'm able to review this pull request.

@darxriggs are you available to assist with the review of this pull request?

**Comment by darxriggs** [comment]
@MarkEWaite I just had a very quick look at the code. I think it would require some time on my side to get familiar with the the changes and concepts to get it right. As I am already busy with some other plugins I am sorry to say that I cannot assist here.

**Comment by MarkEWaite** [comment]
Labeled this pull request to be reviewed in the pull requests related to changelogs.  I won't review it in the next 3 months.  I've assigned it the milestone 'Later' so that it can be reopened when time allows me to review it.

**Comment by gmshake** [comment]
@MarkEWaite Hi, I've noticed that the git-plugin has released version 4.0. Is it appropriate to reopen this PR now?

**Comment by MarkEWaite** [comment]
Yes @gmshake you are welcome to reopen it.  I'm focusing on prioritizing the areas to be reviewed next and ways that others can help with the review and testing of proposed changes.

**Pull request closed without merging**
