### PR TITLE
[JENKINS-33827] Add Compound build chooser

### PR DESCRIPTION
**Pull request by zmeggyesi**
A new build chooser behaviour to combine Inverse and Ancestry build choosers: first the job-specified branches are filtered, then the remaining ones are subjected to an ancestry/age check to determine final revision(s) to build

### CODE REVIEW

**Comment by zmeggyesi** [comment]
@MarkEWaite Did you manage to track down the PermGen error? Is there anything standing in the way of merging this that I can help with?

**Comment by zmeggyesi** [comment]
@MarkEWaite Is there any way to tell what went wrong during the build? I can only see that the build itself succeeded, but no tests ran, however, there is no indication *why* no tests ran or if any did, *which* failed.

**Comment by MarkEWaite** [comment]
Only by reading the build log. Sorry, but that is the only way I know.

**Comment by zmeggyesi** [comment]
@MarkEWaite I managed to get the log file, and I think you have a CI infrastructure problem: 

```
[Pipeline] parallel
[Pipeline] [split0] { (Branch: split0)
[Pipeline] [split1] { (Branch: split1)
[Pipeline] [split2] { (Branch: split2)
[Pipeline] [split0] node
[Pipeline] [split1] node
[Pipeline] [split2] node
[split0] Still waiting to schedule task
[split0] There are no nodes with the label ‘highmem’
[split1] Still waiting to schedule task
[split1] There are no nodes with the label ‘highmem’
[split2] Still waiting to schedule task
[split2] There are no nodes with the label ‘highmem’
Cancelling nested steps due to timeout
```

It looks like there are no nodes to run the tests. Can you (or someone who has the relevant access) check, do I need to tag anyone else to bring it to their attention?

**Comment by MarkEWaite** [comment]
You might try modifying the Jenkinsfile in your pull request to not depends
on highmem

**Comment by zmeggyesi** [comment]
`Jenkinsfile` changes are loaded from `master` due to trust/security restrictions, so whatever changes I make are not reflected in the build process.

BTW, this seems to be the reason all PR tests are failing now, with no way to get them to pass available for non-privileged users. I made the change to remove the dependence, but it will not be used until this branch gets merged or the change is also made on `master`...

**Pull request closed without merging**
