### PR TITLE
[JENKINS-42204] GitSCMSource: Fix backwards compatibility for advanced options

### PR DESCRIPTION
**Pull request by jbq**

### CODE REVIEW

**Comment by MarkEWaite** [comment]
Thanks for investigating this one!  I usually interpret "WIP" to mean "work in progress" and don't start experimenting with a pull request until the "WIP" has been removed.  Is that what you intend?

**Comment by jbq** [comment]
Hi @MarkEWaite yes I'm currently running tests to make sure this PR fixes the backwards-compatibility problem

**Comment by jbq** [comment]
OK tests are successful on my side

**Comment by MarkEWaite** [comment]
Thanks very much!  I'll evaluate it over the next 3-4 days (things are busy at work right now, just return from a holiday yesterday and need to focus on work topics rather than Jenkins).

**Comment by MarkEWaite** [comment]
Have you considered switching from modifying the constructor (and the DataBoundConstructor) to just add another DataBoundSetter and leave the constructor alone?

The class already seems to use DataBoundSetter for other properties, and I assume they are as easy to use from Jelly as the DataBoundConstructor.

**Pull request merged**
