### PR TITLE
add recursive clone option into GitSCM

### PR DESCRIPTION
**Pull request by ohhmm**
## [JENKINS-xxxxx](https://issues.jenkins-ci.org/browse/JENKINS-xxxxx) - summarize pull request in one line

Describe the big picture of your changes here to explain to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, include a link to the issue.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is simply a reminder of what we are going to look for before merging your code. If a checkbox or line does not apply to this pull request, delete it. We prefer all checkboxes to be checked before a pull request is merged_

- [ ] I have read the [CONTRIBUTING](https://github.com/jenkinsci/git-plugin/blob/master/CONTRIBUTING.adoc) doc
- [ ] I have referenced the Jira issue related to my changes in one or more commit messages
- [ ] I have added tests that verify my changes
- [ ] Unit tests pass locally with my changes
- [ ] I have added documentation as necessary
- [ ] No Javadoc warnings were introduced with my changes
- [ ] No spotbugs warnings were introduced with my changes
- [ ] Documentation in README has been updated as necessary
- [ ] Online help has been added and reviewed for any new or modified fields
- [ ] I have interactively tested my changes
- [ ] Any dependent changes have been merged and published in upstream modules (like git-client-plugin)

## Types of changes

What types of changes does your code introduce? _Put an `x` in the boxes that apply. Delete the items in the list that do *not* apply_

- [ ] Dependency or infrastructure update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Further comments

If this is a relatively large or complex change, start the discussion by explaining why you chose the solution you did and what alternatives you considered.

### CODE REVIEW

**Comment by MarkEWaite** [comment]
The plugin already includes several configuration settings that enable various submodule update methods.  Can you explain why the [existing submodule options](https://plugins.jenkins.io/git/#advanced-sub-modules-behaviours) are not sufficient to meet the need?

image

**Comment by ohhmm** [comment]
Hi @MarkEWaite,

There is a case with submodules where it isn't.
Here is simple snippet which does code fetch successfully:
```
if [ -d "<src_dir>" ]; then
  cd <src_dir> && git pull --recurse -j8 --rebase=false
else
  git clone <url> --recursive  --reference-if-able=<other_same_repo> --dissociate <src_dir>
fi
```

Here is the case:

- If some submodules are out of date branches specified in .gitmodules. Setting "Update tracking submodules to tip of branch" option resolves the issue of fetching those.

- if it also has tags which are not specified in .gitmodules the setting "Update tracking submodules to tip of branch" results in an error.

Tried with boost library as tag 1.74 recursive submodule: https://github.com/boostorg/boost/tree/boost-1.74.0 (neither branch or tag specified in .gitmodules)
in conjunction with any other submodule where master branch specified in .gitmodules

**Comment by MarkEWaite** [comment]
Thanks for your patience while I'm learning more about an option to git clone and git fetch that I have never used before.

I think the implementation should use the option `--recurse-submodules` rather than `--recursive` since it is the option included in the git documentation.  I've confirmed that `--recursive` is an alias for `--recurse-submodules`.  I've also confirmed that command line git supports `--recurse-submodules` with git 1.8.3, so it is safe to use that option on all the versions of command line git that are supported by the git client plugin.

Since the Jenkins git client implementation uses `git fetch`, we should look to provide 3 possible values when the "recurse submodules" option is selected.  The options would correspond to the git fetch options, `yes`, `no`, and `on-demand`.

The implementation will also need to extend the GitToolChooser component so that the GitToolChooser will not choose JGit if a recurse submodules option is enabled.

We'll also need tests that confirm the new behavior is operating as expected.

**Comment by ohhmm** [comment]
Thank you very much @MarkEWaite, sounds good.

**Comment by MarkEWaite** [comment]
@ohhmm I'm closing this pull request and will use the concepts we've discussed in a proposal for the [Jenkins project in Google Summer of Code 2021](https://www.jenkins.io/projects/gsoc/#gsoc-2021).

**Pull request closed without merging**
