### PR TITLE
[JENKINS-47531] Allow separate Git LFS credentials

### PR DESCRIPTION
**Pull request by patricklangsonos**
## [JENKINS-47531](https://issues.jenkins-ci.org/browse/JENKINS-47531) - Allow separate Git LFS credentials

The Git-Plugin already had support to do a Git LFS pull, but it didn't have the ability to specify what credentials to use. This is important because you may need separate credentials for a Git backend like GitHub or GitLab, and for a LFS server like Artifactory. Without this change, it would default to using the Git credentials in both places.

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/jenkinsci/git-plugin/blob/master/CONTRIBUTING.adoc) doc
- [x] I have referenced the Jira issue related to my changes in one or more commit messages
- [x] I have added tests that verify my changes
- [x] Unit tests pass locally with my changes
- [x] I have added documentation as necessary
- [x] No Javadoc warnings were introduced with my changes
- [x] No spotbugs warnings were introduced with my changes
- [x] Online help has been added and reviewed for any new or modified fields
- [x] I have interactively tested my changes
- [x] Any dependent changes have been merged and published in upstream modules (like git-client-plugin)

(I'm assuming that javadoc/spotbugs would have been raised with `mvn -e verify`. If that not the case let me know what I'm missing and I can run it)

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Further comments

No other comments - lots of discussion in the issue already

## Acknowledgements
Thanks @mephi42 for #546! This started from that PR and addressed some points raised during review.

### CODE REVIEW

**Comment by MarkEWaite** [comment]
There is a push in the community to make the default include LFS automatically for CLI git versions newer than roughly 2.15.  How well does this technique work with newer versions of CLI git when used outside of Jenkins?

**Comment by patricklangsonos** [comment]
I have been testing this on 2.26.2, which is recent but 2.27.0 is the latest. I haven't tested older than 2.26.x because I have also been evaluating shallow clone and sparse checkout which have a lot of recent improvements.

Are you concerned about the git cli options changing, or something else?

Initially I was hoping to avoid using a separate checkout option for LFS, and instead rely on git to "do the right thing" since I have `.gitattributes` and `.lfsconfig` committed to the repo. Unfortunately, that approach fails because there's a 1:1 mapping between credentials and the repo and I'm not including user/pass in `.lfsconfig`, and the smudge filter is disabled https://github.com/jenkinsci/git-client-plugin/blob/3052db7fd4ce0cfb513ad486745779ffa5d39185/src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java#L2724. I also considered just trying to shell out and cache some extra credentials, but that was thwarted because the existing git-client code always overrides that with `GIT_ASKPASS` https://github.com/jenkinsci/git-client-plugin/blob/3052db7fd4ce0cfb513ad486745779ffa5d39185/src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java#L2003

**Comment by MarkEWaite** [comment]
I was more concerned that https://github.com/jenkinsci/git-client-plugin/pull/476 is proposing to detect newer versions of command line git and newer versions of git LFS and rely on command line git to "do the right thing" with repositories that have LFS enabled.  I wouldn't want to enable the extra password for git LFS in this pull request and then disable the call to git LFS in https://github.com/jenkinsci/git-client-plugin/pull/476 .

I am certain that I have much more to learn about how to use git LFS most effectively inside the git plugin and git client plugin.  Thanks for helping the community and for exploring the alternatives with us.

**Comment by patricklangsonos** [comment]
Thanks! I commented on https://issues.jenkins-ci.org/browse/JENKINS-59139 to keep the conversation on changing defaults in one thread

**Comment by patricklangsonos** [comment]
I also opened an issue since I couldn't find any clear roadmap for Git-LFS https://github.com/git-lfs/git-lfs/issues/4189

**Comment by patricklangsonos** [comment]
Based on that thread in git-lfs/git-lfs, it seems the risk of later breaking changes is low

**Comment by patricklangsonos** [comment]
@MarkEWaite - what would it take to get this merged? Right now I'm going through a cumbersome process of building a fork and storing it in my own maven repo, which is not sustainable in the long term. I'm sure there are others using JFrog Artifactory that need this too. I'm happy to join any community meetings, etc to discuss the LFS design if there are still open questions in the approach and goals.

**Comment by Jmennius** [comment]
There is definitely demand for this, any external LFS server basically requires different credentials (you can rarely match them).
In addition to Artifactory, there is Sonatype Nexus Repository Manager (which is popular as well I guess) and this change is basically a requirement to support LFS on Nexus.

What is holding up?

**Comment by MarkEWaite** [comment]
> There is definitely demand for this, any external LFS server basically requires different credentials (you can rarely match them).
> In addition to Artifactory, there is Sonatype Nexus Repository Manager (which is popular as well I guess) and this change is basically a requirement to support LFS on Nexus.
> 
> What is holding up?

I describe my most significant concern in an [earlier comment](https://github.com/jenkinsci/git-plugin/pull/930#issuecomment-658173496).

A lesser concern is that I don't have access to an Artifactory or a Nexus that acts as an LFS server, so I am unable to confirm this works and remains working.  It needs more users that report "I'm using it in production, it works for me".  Download the latest build of this pull request, install it on your Jenkins controller, configure your jobs to use a separate credential for Git LFS, and report the results as a comment to this pull request.

**Comment by Jmennius** [comment]
> A lesser concern is that I don't have access to an Artifactory or a Nexus that acts as an LFS server, so I am unable to confirm this works and remains working. It needs more users that report "I'm using it in production, it works for me". Download the [latest build](https://ci.jenkins.io/job/Plugins/job/git-plugin/job/PR-930/19/artifact/org/jenkins-ci/plugins/git/4.4.6-rc4129.a14158cdc7f6/git-4.4.6-rc4129.a14158cdc7f6.hpi) of this pull request, install it on your Jenkins controller, configure your jobs to use a separate credential for Git LFS, and report the results as a comment to this pull request.

Thanks, I will test it and report.

One of the [implementations](https://github.com/git-lfs/git-lfs/wiki/Implementations) is the [git-lfs/lfs-test-server](https://github.com/git-lfs/lfs-test-server), which should be really easy to use for testing purposes.

P.S. The link is broken (404) for some reason, I'll try to find the artifact.

**Comment by MarkEWaite** [comment]
> P.S. The link is broken (404) for some reason, I'll try to find the artifact.

The artifact is on the latest build of the "pr-merge" listed in the "checks" section of this page.  Currently, that is [build 19](https://ci.jenkins.io/job/Plugins/job/git-plugin/job/PR-930/19/)

**Comment by Jmennius** [comment]
I can confirm this PR works in my environment with Nexus.

**Comment by Jmennius** [comment]
I was trying to understand your concern with jenkinsci/git-client-plugin#476.

From what I understand, it will make the additional `git lfs pull` step optional (which is now required) and LFS pull will be invoked indirectly by `git checkout` (and `git clone`).
Assuming that the current mechanism doesn't allow to distinguish credential requests between git vs lfs or by host, this will make passing different credentials harder or impossible when doing a `git clone` (both `git pull` and `lfs pull` are executed in the same context)?
In this case we can still require people who want/need to use separate credentials to use separate/additional LFS pull step, for the time being.

It looks to me that the proper way to solve this would be to use git credential helper instead of `GIT_ASKPASS` and `GIT_SSH`.

**Comment by MarkEWaite** [comment]
> It looks to me that the proper way to solve this would be to use git credential helper instead of `GIT_ASKPASS` and `GIT_SSH`.

I don't see how a credential helper would improve this situation.  Does a credential helper have the ability to decide that its credentials should only be provided when authenticating an LFS operation?

I assume there are significant differences between the credential helpers supported with git 1.8 (CentOS 7) and git 2.29.1 (Windows, Debian Testing, Arch Linux, etc.).  The git plugin supports such a wide range of command line git versions that it must be very careful before introducing new requirements or new dependencies.

**Comment by Jmennius** [comment]
> > It looks to me that the proper way to solve this would be to use git credential helper instead of `GIT_ASKPASS` and `GIT_SSH`.
> 
> I don't see how a credential helper would improve this situation. Does a credential helper have the ability to decide that its credentials should only be provided when authenticating an LFS operation?

Yes, it does, but by resource URL. From documentation [1]:
> Git considers each credential to have a context defined by a URL. This context is used to look up context-specific configuration, and is passed to any helpers, which may use it as an index into secure storage.

Basically, in Jenkins, a user should specify a mapping between the credential and a URL - that would totally work with the credential helper.

[1] [gitcredentials](https://git-scm.com/docs/gitcredentials)

---

> I assume there are significant differences between the credential helpers supported with git 1.8 (CentOS 7) and git 2.29.1 (Windows, Debian Testing, Arch Linux, etc.). The git plugin supports such a wide range of command line git versions that it must be very careful before introducing new requirements or new dependencies.

What I am talking about is providing a new (e.g. `git-credential-helper-jenkins`) credential helper (see [2], [1]) that Jenkins would tell git to use.
The credential helpers API did not change since 2.8 as far as I can tell. Plus it is really simple.

You can check out a [git-credential-libsecret](https://github.com/git/git/blob/master/contrib/credential/libsecret/git-credential-libsecret.c) as an example of a really simple yet functional credential helper (it's just an interface between libsecret and git).

[2] [API credentials - Credential helpers](https://git-scm.com/docs/api-credentials#_credential_helpers)

**Comment by patricklangsonos** [comment]
I agree that a separate credential helper could be cleaner because it was designed to handle multiple URLs and would also work where different credentials are required by Git submodule pulls. The scope of that change is much broader though which is why I favored finishing off the previous PR this was based on and deploying it as-is.

**Comment by Jmennius** [comment]
> I agree that a separate credential helper could be cleaner because it was designed to handle multiple URLs and would also work where different credentials are required by Git submodule pulls. The scope of that change is much broader though which is why I favored finishing off the previous PR this was based on and deploying it as-is.

I totally agree with you!

**Comment by slietzau** [comment]
I can confirm build 25 of this PR works with Artifactory.

The following LFS authentication methods were tested:
* API Token (Username + Password)
* SSH (Username + SSH Key)

I agree with the last two comments:
Merge this as soon as possible and add credential manager capabilities to the git plugin in a later step.

**Comment by Korvin32** [comment]
I can confirm the PR build #57 works fine and as desired with Nexus3.
Please merge as soon as possible as we need the ability to specify separate credentials for our Nexus3 while git lfs pull.

**Comment by matt-duke** [comment]
This PR has been open for some time and would be very useful for my organization. Can it be merged or are there blockers?

**Comment by nm515350** [comment]
My company is using this with Jfrog artifactory cloud. I agree, it would be preferable to use a release build with this included.

**Comment by Jmennius** [comment]
@MarkEWaite what is holding this up? Anything we can do?

**Comment by exoemay** [comment]
We would also require this and as we run in an enterprise environment, we can't allow manually compiled plugins. Please merge this soon!

**Comment by rettenbs** [comment]
It works if you use it in a groovy script and pass the parameter to checkout step.

**Comment by exoemay** [comment]
Do you mean to add the entire git checkout step into the Jenkinsfile? We fork our projects a lot, which would mean having to adjust the Jenkinsfile for each fork every time we push things around, breaking PRs, etc. Unless I don't need to specify the git url for this.

Do you maybe have a snippet for me?

**Comment by rettenbs** [comment]
@exoemay Our checkout is quite complex so we cannot rely on the configuration options in Jenkins anyway.

We are basically doing something like this (assuming that the variables `branch`, `lfsCredentials`, `gitCredentials`, and `url` are set correctly, e.g. via parameters):
```
checkout([$class: 'GitSCM',
    branches: [[name: branch]],
    extensions: [[$class: 'GitLFSPull',
        credentialsId: lfsCredentials]],
    userRemoteConfigs: [[
        credentialsId: gitCredentials,
        url: url]]])
```

I think there is also a way to modify `scm` if you are just doing `checkout scm` but I have not tested that.

**Comment by Jmennius** [comment]
Sadly, we face the same issue as @exoemay - credentials configuration is not saved when configured via UI.
It was working before. The only thing that changed since then is Jenkins version we use. Maybe there was an API change?

**Comment by Jmennius** [comment]
@patricklangsonos any chance you can look into what the issue might be? I went through the code and some changes but couldn't find anything...

**Comment by patricklangsonos** [comment]
I haven't been using this in newer versions of Jenkins, so I'm not sure what changed. I moved to using SSH auth to Artifactory because this was not merged and I could manage SSH agents outside of Jenkins' secrets model.

**Comment by patricklangsonos** [comment]
I'm going to close this request since there doesn't seem to be a concrete path to getting it merged, and I have stopped using this change in my production environments in favor of SSH-based auth. If someone else wants to pick it up, feel free.

**Comment by Jmennius** [comment]
I will mention a workaround that to get separate LFS credentials: on a Jenkins node, configure a [git credential helper](https://git-scm.com/docs/gitcredentials) to [store](https://git-scm.com/docs/git-credential-store) and save the credentials in the config file.
Not nice, but at least it works.
It must be said, a bit of a disappointing experience 😞

**Comment by DoktorZ** [comment]
That is really not the solution we was waiting the whole time for.
Thank you @Jmennius for providing your workaround.

**Pull request closed without merging**
