### PR TITLE
JENKINS-48431 Support both lightweight checkout AND build parameters

### PR DESCRIPTION
**Pull request by tgatinea**
[JENKINS-48431](https://issues.jenkins-ci.org/browse/JENKINS-48431) Support both lightweight checkout AND build parameters

To support both lightweight checkout AND build parameters, we need to:

- recover the environment parameters of the build
- evaluate the SCM structure according to the build environment parameters

This leads to implement a new method into scm-api-plugin:
public static SCMFileSystem of(@nonnull Run build, @nonnull SCM scm, @checkfornull SCMRevision rev)

And it leads to implement:
public SCMFileSystem build(@NonNull Run build, @NonNull SCM scm, @CheckForNull SCMRevision rev)

This method recovers from the current build the environment parameters and evaluate the SCM structure with the environment parameters.

It also does a git fetch with the refspec if the refspec is set in SCM.

It also take into account the case of a gerrit trigger with:
- SCM refspec set to $GERRIT_REFSPEC
- SCM branch set to FETCH_HEAD

This is done between lines 360 to 369

Note that this modification is in relation with two other pull requests that concerns:
- workflow-cps-plugin: https://github.com/jenkinsci/workflow-cps-plugin/pull/329
- scm-api-plugin: https://github.com/jenkinsci/scm-api-plugin/pull/78

Note that this pull request will not work if the pull request for scm-api-plugin is not valdated

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is simply a reminder of what we are going to look for before merging your code. If a checkbox or line does not apply to this pull request, delete it. We prefer all checkboxes to be checked before a pull request is merged_

- [ ] I have read the [CONTRIBUTING](https://github.com/jenkinsci/git-plugin/blob/master/CONTRIBUTING.md) doc
- [X] I have referenced the Jira issue related to my changes in one or more commit messages
- [ ] I have added tests that verify my changes
- [ ] Unit tests pass locally with my changes
- [ ] I have added documentation as necessary
- [X] No Javadoc warnings were introduced with my changes
- [X] No spotbugs warnings were introduced with my changes
- [X] I have interactively tested my changes
=> I have tested my changes though workflow-cps-plugin under hpi
- [ ] Any dependent changes have been merged and published in upstream modules (like git-client-plugin)
=> This pull request depends closely to the scm-api-plugin

## Types of changes

What types of changes does your code introduce? _Put an `x` in the boxes that apply. Delete the items in the list that do *not* apply_

- [ ] Dependency or infrastructure update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Further comments

If this is a relatively large or complex change, start the discussion by explaining why you chose the solution you did and what alternatives you considered.

### CODE REVIEW

**Comment by tgatinea** [comment]
@MarkEWaite I'm familiar with delivering plugins that gets dependencies. 
Do I need to wait the end of the pull request https://github.com/jenkinsci/scm-api-plugin/pull/78 before having some feedback for the git-plugin code?
Thanks by advance

**Comment by MarkEWaite** [comment]
You don't need to wait until the end of pull request https://github.com/jenkinsci/scm-api-plugin/pull/78 before receiving feedback on the git plugin code.  A reviewer could provide feedback based on the combination of pull requests.

I have limited time for review of pull requests and many other pull requests that I consider higher priority than your request to support lightweight checkout and build parameters.  I will not review your pull request for a long time.

Top themes that I've prioritized include:

1. [BuildData bloat fix](https://github.com/jenkinsci/git-plugin/pulls?q=label%3A%221+-+BuildData%22+is%3Aclosed) [JENKINS-19022](https://issues.jenkins-ci.org/browse/JENKINS-19022)
2. [Build initiation improvements - notifyCommit and others](https://github.com/jenkinsci/git-plugin/pulls?q=label%3A%222+-+notifyCommit%22+is%3Aclosed) [JENKINS-29603](https://issues.jenkins-ci.org/browse/JENKINS-29603), [JENKINS-50168](https://issues.jenkins-ci.org/browse/JENKINS-50168), [JENKINS-25048](https://issues.jenkins-ci.org/browse/JENKINS-25048)
3. [Submodule improvements](https://github.com/jenkinsci/git-plugin/pulls?q=label%3A%223+-+Submodules%22+is%3Aclosed)
4. [Caching for better performance and reduced disc use](https://github.com/jenkinsci/git-plugin/pulls?q=label%3A%224+-+Caching%22+is%3Aclosed)
5. [Changelog improvements](https://github.com/jenkinsci/git-plugin/pulls?q=label%3A%225+-+Changelog%22+is%3Aclosed)

Other maintainers may have different priorities and different objectives.  You're certainly welcome to check with @rsandell and @fcojfernandez on their priorities.

**Comment by hkrpavan** [comment]
@tgatinea were you able to generate plugin with this change? Do you have a private .hpi file to share with?

**Comment by tgatinea** [comment]
@hkrpavan Were you able to recompile the 3 plugins :
- scm-api-plugin should be version 2.6.4-SNAPSHOT and need to be installed on jenkins first

- I patched git-plugin from version stable-3.x 
=> But now last version is 4.0.0 and I cannot recompile anymore
=> I probably have to rework
This plugin is to be installed after previous plugin

- workflow-cps-plugin was coming from 2.74 and it is now at 2.77

When I'll have time I will move to the last versions and push my code

**Comment by hkrpavan** [comment]
@tgatinea , Thanks for the reply. I could able to build these plugins from top of master branch and make it working. This works good with declarative pipelines. Now i bumped in to https://issues.jenkins-ci.org/browse/JENKINS-56943, though a different problem altogether.

**Comment by tgatinea** [comment]
@hkrpavan I have found why git-plugin does not compile anymore.
In my patch, I have :
                String refspec = environment.expand(config.getRefspec()).trim();
                String head = headName;
                if (refspec == null) { ...

The spotbugs "mvn spotbugs:gui" complain that refspec cannot be null because String.trim() cannot be with a String null.
But in fact it can be the case as config.getRefspec() can return null value.

Now, if I code something like:
                String refspec = environment.expand(config.getRefspec());
                if (refspec != null) {
                    refspec = refspec.trim();
                }
                String head = headName;
                if (refspec == null) { ...

Then it compiles because "refspec = environment.expand(config.getRefspec())" can be null.

**Comment by hkrpavan** [comment]
@tgatinea Thank you, i could able to build git-plugin with your latest changes from top if master branch.

**Comment by vpod** [comment]
@hkrpavan : so, let's vote and contribute both changes :-)

**Comment by jetersen** [comment]
I have expanded the changes to include GitSCMTelescope and GitSCMFileSystem and removed the duplication :)

**Comment by jetersen** [comment]
@vpod @hkrpavan I created https://github.com/jenkinsci/workflow-multibranch-plugin/pull/98 to solve the readTrusted step :)

**Comment by jetersen** [comment]
FYI I just deployed all the bits to our production server 💪 and our job passed successfully. https://github.com/jenkinsci/git-plugin/pull/898#issuecomment-633956118

**Comment by jetersen** [comment]
if anyone else wants the bits. I have deployed them to repo.jenkins-ci.org

https://repo.jenkins-ci.org/snapshots/org/jenkins-ci/plugins/scm-api/2.6.4-SNAPSHOT/scm-api-2.6.4-20200525.215035-2.hpi
https://repo.jenkins-ci.org/snapshots/org/jenkins-ci/plugins/workflow/workflow-cps/2.81-SNAPSHOT/workflow-cps-2.81-20200526.095117-1.hpi
https://repo.jenkins-ci.org/snapshots/org/jenkins-ci/plugins/workflow/workflow-multibranch/2.22-SNAPSHOT/workflow-multibranch-2.22-20200526.094121-1.hpi
https://repo.jenkins-ci.org/snapshots/org/jenkins-ci/plugins/git/4.3.0-SNAPSHOT/git-4.3.0-20200525.225217-1.hpi

**Comment by MarkEWaite** [comment]
Superseded by #898

**Pull request closed without merging**
