### PR TITLE
Add support for SCM Name environment variables for multi-scm builds

### PR DESCRIPTION
**Pull request by mklein0**
One of the difficulties of using the Git plugin in a Multi-SCM environment is it uses the same variables names for each SCM added in a multi-SCM Jenkins build context. To alleviate this issue without altering current behavior of allowing overwrites, an additional environmental variable will be set prefixed/namespaced by the SCM Name set for the repository. This should allow the decoding the state of multiple repositories easier. If no SCM Name is set, no additional variables are set.

In addition to the environment variable change, there is a change to the plugin configuration templates to work-around the issue that the SCMD parameter is being set incorrectly in when derived via the Multi-SCM plugin.

### CODE REVIEW

**Comment by mklein0** [comment]
Looks like 700921b runs a foul one of the unit tests.  This can be backed out. This is change a separate change to the plugin configuration templates to work-around the issue that the SCMD parameter is being set incorrectly in when derived via the Multi-SCM plugin.

**Comment by jason-womack** [comment]
When can we expect this to be integrated into a release?

**Comment by MarkEWaite** [comment]
It will likely be several months before this is evaluated.

**Comment by mklein0** [comment]
The unit test (hudson.plugins.git.GitSCMTest.testFetchFromMultipleRepositories) which fails appears to fail intermittently due to the use of a HashMap for ordering the list of repos with changes available.

- https://github.com/jenkinsci/git-plugin/blob/git-2.5.3/src/main/java/hudson/plugins/git/util/DefaultBuildChooser.java#L72
- https://github.com/jenkinsci/git-plugin/blob/git-2.5.3/src/main/java/hudson/plugins/git/GitSCM.java#L994

The polling check to restrict the second candidate list:
- https://github.com/jenkinsci/git-plugin/blob/git-2.5.3/src/main/java/hudson/plugins/git/util/DefaultBuildChooser.java#L134

is disable here:
- https://github.com/jenkinsci/git-plugin/blob/git-2.5.3/src/main/java/hudson/plugins/git/GitSCM.java#L984-L985

**Comment by MarkEWaite** [comment]
@mklein0 thanks for the analysis of the intermittent failures. Any recommendation on the best way to resolve the issue?

**Comment by mklein0** [comment]
@MarkEWaite The determineRevisionToBuild method needs to be aware if the build is triggered as a result of polling or not so it can set the isPollingCall parameter of the getCandidateRevisions method.

If the isPollingCall parameter is set, the getHeadRevision of the DefaultBuildChooser class will filter out the previous commit built.

I do not know the logic of the code well enough to tell you why the isPollingCall parameter is hard coded to true in the determineRevisionToBuild method.

**Pull request closed without merging**
