### PR TITLE
[FIXED JENKINS-18666] Submodule reference

### PR DESCRIPTION
**Pull request by lkraider**
Addresses https://issues.jenkins-ci.org/browse/JENKINS-18666

### CODE REVIEW

**Comment by lkraider** [comment]
Yes, you can create a reference repository that combines to mirror multiple submodules, it is just a matter of adding multiple remotes.

And that is exactly the use case here, quite standard I believe for projects that handle many large ones since it makes syncing the one mirror easier (a simple `git fetch --all`).

**Comment by MarkEWaite** [comment]
Thanks for the clarification. Can the technique of combining multiple reference repositories into a single super repository be mentioned somewhere in the help text?

I'm accustomed to thinking of a reference repository as a copy of a single repository rather than as the union of many different repositories. I suspect other users may have my same incomplete understanding of the uses of reference repositories.

**Comment by lkraider** [comment]
I added some general instructions on the help file.

**Comment by kroatoa** [comment]
Hi, 
after reading the above comments I am unclear if anything is blocking this. I would be interested in having this fix in to speed up our jenkins job significantly. Current we are forced to update the submodules manually. Using the git plugin for this would be preferrable.

**Comment by MarkEWaite** [comment]
I ran an hour of focused tests looking for compatibility issues in upgrading from the previous plugin version to a version with this addition.  I found no issues.  The submodule reference setting is honored, and the expected message is reported when the reference directory is defined in the job but does not exist on the file system.  I'd like to do one more code review, and a deeper look at the tests, then I believe it is ready to merge to the master branch for inclusion in git plugin 2.4.1.

I don't yet have a proposed date for git plugin 2.4.1, but hope to release it within a month.

**Comment by kroatoa** [comment]
Thank you for your effort. 
That is great news, and I look forward to the next release.

**Pull request merged**
