### PR TITLE
JENKINS-50366 - Implement --first-parent option in changelog

### PR DESCRIPTION
**Pull request by zambamingi**
[JENKINS-50366](https://issues.jenkins-ci.org/browse/JENKINS-50366) - Implement --first-parent option in changelog

In some cases, the changelog on a branch should only show changes from that branch and not show any changes from the branch being merged in.  The --first-parent option limits the changelog to show only changes on the branch.

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/jenkinsci/git-plugin/blob/master/CONTRIBUTING.md) doc
- [x] I have referenced the Jira issue related to my changes in one or more commit messages
- [x] I have added tests that verify my changes
- [x] Unit tests pass locally with my changes
- [x] I have added documentation as necessary
- [x] No Javadoc warnings were introduced with my changes
- [x] No findbugs warnings were introduced with my changes
- [x] I have interactively tested my changes
- [ ] Any dependent changes have been merged and published in upstream modules (like git-client-plugin)

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by MarkEWaite** [comment]
You can fix the failing build in your pull request by updating the git-client dependency in the pom.xml file to depend on git-client version 3.0.0-beta6-rc1867.204c85557f8c.  The git client plugin and git plugin are both using "incrementals" now, which means that even CI builds are available for dependency during development.

We won't ship the final release with that incremental dependency, but it is a great way to show that there is a dependency on git client and that the dependency is satisfied.

**Comment by Marty** [comment]
Thanks for your work! We recently ran into this too and are eagerly waiting for this to be released :)

**Comment by zambamingi** [comment]
Is there something I can do to make sure this can be merged?  What does the Later milestone mean?

**Comment by MarkEWaite** [comment]
The Later milestone means that I'll reopen this pull request when my review timeline allows me to spend the effort to evaluate the pull request.  My current priorities are:

1. Resolve the git plugin 4.0.0 regressions  which prevent it from being released (see the [4.0 milestone](https://github.com/jenkinsci/git-plugin/milestone/3) for the list of those issues)
2. Release another beta of git plugin 4.0.0 to confirm regressions are resolved
3. Review change log related pull requests (see the [changelog label](https://github.com/jenkinsci/git-plugin/pulls?q=label%3A%222+-+notifyCommit%22+is%3Aclosed))
4. Review submodule related pull requests (see the [submodules label](https://github.com/jenkinsci/git-plugin/pulls?q=label%3A%223+-+Submodules%22+is%3Aclosed+milestone%3ALater))
5. Review caching related pull requets (see the [caching label](https://github.com/jenkinsci/git-plugin/pulls?q=label%3A%224+-+Caching%22+is%3Aclosed+milestone%3ALater))
6. Review changelog related pull requests (see the [changelog label](https://github.com/jenkinsci/git-plugin/pulls?q=label%3A%225+-+Changelog%22+is%3Aclosed+milestone%3ALater))

**Comment by zambamingi** [comment]
Sounds good, thanks for the explanation.

**Pull request closed without merging**
