### PR TITLE
Use relative URLs for documentation images (images:/ to images:)

### PR DESCRIPTION
**Pull request by halkeye**
Related to https://github.com/jenkins-infra/plugin-site/pull/961/ - some of the current images are linked to the root of the repo.

I'm leaving it as draft as I'm not sure what the right solution is yet.

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/jenkinsci/git-plugin/blob/master/CONTRIBUTING.adoc) doc
- [x] I have referenced the Jira issue related to my changes in one or more commit messages
- [x] Unit tests pass locally with my changes
- [x] I have added documentation as necessary
- [x] No Javadoc warnings were introduced with my changes
- [x] No spotbugs warnings were introduced with my changes
- [x] Documentation in README has been updated as necessary
- [x] Online help has been added and reviewed for any new or modified fields
- [x] I have interactively tested my changes
- [x] Any dependent changes have been merged and published in upstream modules (like git-client-plugin)

## Types of changes

- [x] Dependency or infrastructure update

### CODE REVIEW

**Comment by MarkEWaite** [comment]
I think it is an improvement and a good correction, even if it does not ultimately resolve the issue you're fixing.

**Review by MarkEWaite — APPROVED** [review]

**Comment by MarkEWaite** [comment]
@halkeye any reason that I should not merge this improvement?

**Comment by halkeye** [comment]
Honestly? It's selfishly my test case for plugins site. It's currently not breaking anything and its a known scenario so I was gonna dig into it once I finish Jenkins it the way

**Comment by MarkEWaite** [comment]
> Honestly? It's selfishly my test case for plugins site. It's currently not breaking anything and its a known scenario so I was gonna dig into it once I finish Jenkins it the way

Super.  I'll leave it in draft and not worry about it.  If it is helping you and not hindering you, then I'm happy to have it remain as a draft PR

**Review by MarkEWaite — APPROVED** [review]

**Comment by MarkEWaite** [comment]
I merged this since I believe that @halkeye is not active on the plugins site any longer.

**Pull request merged**
