### PR TITLE
[JENKINS-54858] Init Org/Repo Name regex

### PR DESCRIPTION
**Pull request by Hrushi20**
## [JENKINS-54858](https://issues.jenkins.io/browse/JENKINS-54858) - Adds Organization/Project and Repository name

Added a global git config for regex which is used internally to get the project name and repo name.

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/jenkinsci/git-plugin/blob/master/CONTRIBUTING.adoc) doc
- [ ] I have added tests that verify my changes
- [x] No Javadoc warnings were introduced with my changes
- [x] No spotbugs warnings were introduced with my changes
- [ ] I have interactively tested my changes

## Types of changes

What types of changes does your code introduce? _Put an `x` in the boxes that apply. Delete the items in the list that do *not* apply_
fixes an issue)

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by krisstern** [comment]
A summary of the issue at JIRA: https://issues.jenkins.io/browse/JENKINS-54868

So let's compile a list of URLs you are expected to handle with your regex:

```
ssh://markwaite@vs-ssh.visualstudio.com:22/DefaultCollection/_ssh/elisp
ssh://git@github.com/MarkEWaite/tasks.git
ssh://git.assembla.com/git-plugin.bin.git
https://www.assembla.com/spaces/git-plugin/git-2/
https://markwaite.visualstudio.com/_git/elisp
https://markwaite.visualstudio.com/DefaultCollection/_git/elisp
https://markwaite.visualstudio.com/DefaultCollection/elisp/_git/elisp
https://markwaite:password-here@markwaite.visualstudio.com/DefaultCollection/_git/elisp
https://markewaite:password-here-also@bitbucket.org/markewaite/tasks.git
https://markewaite:password-here-as-well@bitbucket.org/markewaite/bin.git
https://markewaite@bitbucket.org/markewaite/tasks.git
https://markewaite@bitbucket.org/markewaite/git-client-plugin.git
https://markewaite@bitbucket.org/markewaite/bin.git
https://MarkEWaite:also-a-password@gitlab.com/MarkEWaite/tasks.git
https://MarkEWaite:another-password@github.com/MarkEWaite/tasks.git
https://MarkEWaite:yes-this-is-a-password@github.com/MarkEWaite/bin.git
https://jenkins-git-plugin.git.beanstalkapp.com/git-client-plugin.git
https://gitlab.com/MarkEWaite/tasks.git
https://gitlab.com/MarkEWaite/tasks
https://gitlab.com/MarkEWaite/bin
https://github.com/MarkEWaite/tasks.git
https://github.com/MarkEWaite/bin.git
https://git.assembla.com/git-plugin.bin.git
https://bitbucket.org/markewaite/tasks.git
https://bitbucket.org/markewaite/git-client-plugin.git
https://bitbucket.org/markewaite/bin.git
git@jenkins-git-plugin.git.beanstalkapp.com:/jenkins-git-plugin/git-client-plugin.git
git@gitlab.com:MarkEWaite/tasks.git
git@github.com:MarkEWaite/tasks.git
git@github.com:MarkEWaite/bin.git
git@git.assembla.com:git-plugin.bin.git
git@bitbucket.org:markewaite/tasks.git
git@bitbucket.org:markewaite/bin.git
```

Also, please note that
> Our hosts include [GitHub](https://github.com/), [Gitlab](https://about.gitlab.com/), [AzureDevOps Server/TFS](https://docs.microsoft.com/en-us/azure/devops/?view=azure-devops) (on-prem), [Gogs](https://gogs.io/) some just [file://](file:///), ([Mark Waite](https://issues.jenkins.io/secure/ViewProfile.jspa?name=markewaite) has listed more (above), like Assembla and BitBucket). Azure DevOps Server nomenclature is actually:
http://tfs.mycorp.com/tfs/<TeamCollection>/<TeamProject>/_git/<RepoName>, so it's more than just <OrgName>/<Reponame>.
> Some of our host servers end in an internal domain which is not (com|org), We also don't need to supply a FQDN either; HOST will suffice.

**Comment by Hrushi20** [comment]
```.*(@|\/\/).*?(\/|:)(?<group>.*?)\/(?<repo>.*)$``` works with github,gitlab and bitbucket urls. The vscode and assembla urls are not working with this regex. Trying a way of not hard coding the names into the regex.

**Comment by krisstern** [comment]
Yeah, you should have a list of regex patterns you can match against one-by-one. That way you get to catch all of the possible patterns without having one global URL regex pattern which may become unwieldy.

**Comment by Hrushi20** [comment]
I moved all the tests to a new class. I tried setting the global config regex by calling the GitSCM.DescriptorImpl in my custom test class. Also I created a few test cases. When trying to run the test, I am getting an error stating-
`Jenkins.instance is missing. Read the documentation of Jenkins.getInstanceOrNull to see what you are doing wrong`

How do I set the global config and use it to valid the tests.

**Comment by Hrushi20** [comment]
For now I am passing the global Regex as a parameter. After passing all the tests I will use the global config Regex.

**Comment by MarkEWaite** [comment]
Does a reference to JENKINS-54858 really become a link automatically now?

**Pull request closed without merging**
