### PR TITLE
Remove powermock and the lone test that uses it

### PR DESCRIPTION
**Pull request by MarkEWaite**
Powermock creates problems in JDK 11.
It has not helped the testing and delivery of the plugin in any significant way.

## Remove powermock and the lone test that uses it

Already removed from the master branch for JDK 11 work.  Remove from the stable-3.9 branch because the test is not adding enough value to justify the JDK 11 disruption it causes.

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/jenkinsci/git-plugin/blob/master/CONTRIBUTING.md) doc
- [x] Unit tests pass locally with my changes
- [x] I have added documentation as necessary
- [x] No Javadoc warnings were introduced with my changes
- [x] No findbugs warnings were introduced with my changes
- [x] Any dependent changes have been merged and published in upstream modules

## Types of changes

- [x] Non-breaking change which fixes an issue with JDK 11

## Further comments

If this is a relatively large or complex change, start the discussion by explaining why you chose the solution you did and what alternatives you considered.

### CODE REVIEW

**Comment by batmat** [comment]
@MarkEWaite I hope you do not mind, I just added two commits cherry-picking two `Jenkinsfile` changes from the master branch. That will help making sure we do also test JDK11 *and* JDK8 on the 3.9 branch, not only `master`.

**Comment by MarkEWaite** [comment]
@batmat I'll be surprised (and delighted) if the stable-3.9 branch builds with Java 11.  It depends on Jenkins 1.642.3 and Java 7.  I can always revert your changes if they don't build, or can force push them to remove them from the pull request.  Thanks for reviewing!

**Comment by batmat** [comment]
Right, I missed that, and have to admit I didn't test locally :man_facepalming:. What was I thinking...

Do you BTW feel strongly about keeping these baselines, or would you be fine to bump them too in that branch? For instance if I try to limit to 2.60.3 (as the first requiring Java 8 as you know).

**Comment by MarkEWaite** [comment]
I'm not willing to bump to 2.60.3 in git plugin 3.9.  That's what was done in 4.0.  

My local CI job has shown failures from at least one of the two commits that was added (enforcer rule failures with Jenkins 2.164.1 on Java 11 and Java 8).  You can see the same failures with:

```
$ mvn -Djenkins.version=2.164.1 clean install
```

If you can attempt to resolve the enforcer issues, that would be great.  If not, I'll investigate if time allows after work today.  We're in a middle of a huge winter storm in Colorado now, so I'll be home all night.

**Comment by MarkEWaite** [comment]
@batmat I resolved the enforcer complaints about annotation indexer version and sshd version and then hit a "hard stop" with enforcer complaints that some of the packages allow Java 7 as minimum version.

I'm not willing to move the stable-3.9 branch to require Java 8 and require a much newer Jenkins version.  That's all in git plugin 4.0.

**Pull request merged**
