### PR TITLE
JENKINS-31108 Allow publishing from shallow clone

### PR DESCRIPTION
**Pull request by loomchild**
Previously this operation was forbidden in versions of Git CLI < 1.9.0
(see http://stackoverflow.com/q/6900103 for more details).

Now this operation will succeed using newer client version, but it will
fail when using an old version due to
https://github.com/jenkinsci/git-client-plugin/pull/192

### CODE REVIEW

**Comment by loomchild** [comment]
This should be merged after https://github.com/jenkinsci/git-client-plugin/pull/192 is merged. 

I wasn't sure whether I should also update git-client to 1.19.1-SNAPSHOT in pom.xml in this pull request.

**Comment by MarkEWaite** [comment]
I've reviewed and accepted the change to git-client-plugin. Once that has been built into git-clent 1.19.1-SNAPSHOT (by the Cloudbees servers), please update the pom to point to that version of git-client.

When git-client 1.19.1 is released, I'll then update the pom in git-plugin to depend on 1.19.1.

**Comment by loomchild** [comment]
Thanks a lot for meging the change in git-client-plugin. 1.19.1-SNAPSHOT is still not available in http://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/git-client/. Is it normal or do I need to trigger the build manually somehow?

**Comment by loomchild** [comment]
@MarkEWaite I see that git-client-plugin build now passes (https://jenkins.ci.cloudbees.com/job/plugins/job/git-client-plugin/), but the version 1.19.1-SNAPSHOT is still not available in maven repository. Can you help me generating and deploying it, so this pull request will compile?

**Comment by firon** [comment]
Now that 1.19.2 for the git client plugin is out with the shallow clone changes, can this one be merged and released?

**Comment by loomchild** [comment]
It was possible to merge it since 1.19.1 was released. 

I have updated my commit to bump git-client-plugin version to 1.19.2.

**Comment by firon** [comment]
@MarkEWaite any chance you could review this PR when you have a moment?

I tested it out in my own fork and it's working great, but would be nice to have an official release with it. :D

**Comment by MarkEWaite** [comment]
I included a test for this in my Docker based end to end testing setup. The unit tests in the git client plugin confirm low level functions and the Docker based end to end tests confirm that the tag is really published, from both command line git (which supports shallow clone) and JGit (which does not support shallow clone)

**Pull request merged**
