### PR TITLE
JENKINS-51280 - skip checkout extension got GitSCM

### PR DESCRIPTION
**Pull request by pdinc-oss**
todo: automated tests - manual tests passed and the code is in production use

## [JENKINS-51280](https://issues.jenkins-ci.org/browse/JENKINS-51280) - added extension to support skipping checkout operation

On our integration systems there are users and large 2+GB source bases. We are using Jenkins to automate updates to the source base, but a checkout is disruptive when not meeting all the require criteria. This extension allows the checkout method to skip the actual git checkout.

I may need some guidance on authoring tests for Jenkins / Git SCM plugin.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is simply a reminder of what we are going to look for before merging your code._

- [X] I have read the [CONTRIBUTING](https://github.com/jenkinsci/git-plugin/blob/master/CONTRIBUTING.md) doc
- [X] I have referenced the Jira issue related to my changes in one or more commit messages
- [ ] I have added tests that verify my changes
- [ ] Unit tests pass locally with my changes
- [X] I have added documentation as necessary
- [ ] No Javadoc warnings were introduced with my changes
- [ ] No findbugs warnings were introduced with my changes
- [X] I have interactively tested my changes
- [X] Any dependent changes have been merged and published in upstream modules (like git-client-plugin)

## Types of changes

What types of changes does your code introduce? _Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Further comments

If this is a relatively large or complex change, start the discussion by explaining why you chose the solution you did and what alternatives you considered.

A lot of google searches - unanswered pages asking for the same feature.
e.g. 

- https://stackoverflow.com/questions/29263538/monitor-a-repository-in-jenkins-but-dont-pull
- http://jenkins-ci.361315.n4.nabble.com/Configure-Hudson-To-Poll-SCM-But-Prevent-Checkout-Update-td624303.html
- for pipeline (but does not fetch then)  https://devops.stackexchange.com/a/1074 and https://jenkins.io/doc/book/pipeline/syntax/#options

### CODE REVIEW

**Comment by MarkEWaite** [comment]
Can you further explain the use cases for such an extension?

If a declarative Pipeline does not want to perform a checkout, then the `skipDefaultCheckout` option can be used to skip the default checkout.  If a checkout is needed, it can then be performed elsewhere within the declarative Pipeline.

If a scripted Pipeline does not want to perform a checkout, it should not call the `checkout scm` step.

**Comment by pdinc-oss** [comment]
Fetch is required, but modifying the working directory needs to be avoided until further business logic is performed. And in the very specific case we need to do the merge in a special security context otherwise the system will not have access to the files.

Here is what happens, it is all normal but skips the checkout section.

```
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://XXXXXXXXXXXXXXXXXXXX.mil/di2e/bitbucket/scm/cmis/cmis.git # timeout=10
Fetching upstream changes from https://XXXXXXXXXXXXXXXXXXXX.mil/di2e/bitbucket/scm/cmis/cmis.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials YYYYYYYYYYY
 > git fetch --tags --progress https://XXXXXXXXXXXXXXXXXXXX.mil/di2e/bitbucket/scm/cmis/cmis.git +refs/heads/*:refs/remotes/origin/*
Seen branch in repository origin/bugfix/CMIS-109-remove-hard-coded-auth-replace-with
Seen branch in repository origin/bugfix/CMIS-388-investigate-remediation-fortify
Seen branch in repository origin/bugfix/CMIS-565-cmis-v5.10.4.3-fortify-report-24-apr-2018
Seen branch in repository origin/dev
Seen branch in repository origin/feature/CMIS-368-remove-hard-coded-values-from-dots
Seen branch in repository origin/hotfix/CMIS-568-proper-handling-of-x509-certificates-for-login
Seen branch in repository origin/master
Seen branch in repository origin/test-jira
Seen 8 remote branches
 > git show-ref --tags -d # timeout=10
Skipping check out operation for Revision 951e3a71a465b96c66dabd00b7d4e00c25bbcbb3 (origin/dev)
Commit message: "Autocommit: SCM Byassed - CMIS Dev"
 > git rev-list --no-walk d8030cf3de9304fac4ae47dd491aaf774e8fb72f # timeout=10

```
Now, the custom script can take over having confidence that the Jenkins process ensured the fetch, set the env vars, etc. For example:

```
cd /mnt/local/repo/cmis-dev/
branch=$(git rev-parse --abbrev-ref HEAD)
# some logic here....
git push origin HEAD:dev && git branch -f dev origin/dev && git symbolic-ref HEAD refs/heads/dev && rm -vf "$(mktemp.exe -p src/htdocs/ watch.XXXXXX.tmp)"

```

All of this is to have a minimal deviation from out of the box and comply with existing requirements for the environment.

**Comment by pdinc-oss** [comment]
This is also useful for the older Freestyle project. They are still in use and that is what this is being used in as well.

**Comment by thuongshoo** [comment]
I have checked the Jenkins log. It seems that this ticket is OK.
@pdinc-oss : Can you trigger Pull Request again ?

I'm also interested in this ticket. I set up three jobs for three reference repositories. Other jobs use these repositories as their reference reposipotories. So the reference repositories don't need to checkout, just fetch. As they don't checkout so they also don't need schedule more builds to catch up as [this line](https://github.com/jenkinsci/git-plugin/blob/5b902888e5a0d2bfd2226425dc6cd7ad870cfebb/src/main/java/hudson/plugins/git/GitSCM.java#L1100)

**Comment by pdinc-oss** [comment]
no sure, how to trigger this pull request...

**Pull request closed without merging**
