### PR TITLE
[JENKINS-68562] Fix Git checkouts for controllers running on Windows

### PR DESCRIPTION
**Pull request by dwnusbaum**
## [JENKINS-68562](https://issues.jenkins.io/browse/JENKINS-68562) Fix Git checkouts for controllers running on Windows

The security fix in https://github.com/jenkinsci/git-plugin/commit/b295606e0b865c298fde27bea14f9b7535a976e6 broke all Git checkouts that use remotes with an explicit protocol on Jenkins controllers running on Windows. This PR fixes that issue by catching `InvalidPathException` in the relevant location.

I have not tested the PR (I do not have access to a Windows machine right now). I am not sure if we easily can create automated tests with non-`file` remotes that would exercise this behavior. We should be able to test it at surface level using mocks or maybe via a complex `WireMock` harness for a more thorough test.

Just filing a draft PR for now since I have not tested anything.

CC @Pldi23 

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/jenkinsci/git-plugin/blob/master/CONTRIBUTING.adoc) doc
- [x] I have referenced the Jira issue related to my changes in one or more commit messages
- [x] I have added tests that verify my changes
- [x] Unit tests pass locally with my changes
- [x] I have added documentation as necessary
- [x] No Javadoc warnings were introduced with my changes
- [x] No spotbugs warnings were introduced with my changes
- [x] Online help has been added and reviewed for any new or modified fields
- [x] I have interactively tested my changes

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by MarkEWaite** [comment]
I've confirmed with interactive testing on Windows that the change resolves the issue as reported in JENKINS-68562

**Comment by MarkEWaite** [comment]
I think we want the destination branch to be the v4.11.x branch rather than the master branch so that we can release the change with as few differences as possible.  The changes on the master branch seem fine, but being more conservative in this case seems worth the effort.

**Comment by dwnusbaum** [comment]
@MarkEWaite Ok, up to you as far as basing this against v4.11.x vs master. Daniel and I also discussed it, and the changes between those versions seemed pretty harmless so we figured it probably wouldn't matter either way.

**Comment by MarkEWaite** [comment]
> @MarkEWaite Ok, up to you as far as basing this against v4.11.x vs master. Daniel and I also discussed it, and the changes between those versions seemed pretty harmless so we figured it probably wouldn't matter either way.

That sounds great to me.  Targeting the master branch is actually easier for me.

I've run the unit test on Windows with the change and confirmed that the test passes.

I've run the unit test on Windows without the change and confirmed that the test fails.

Thanks for writing the test!

**Comment by dwnusbaum** [comment]
Ok, given the new unit test and that @MarkEWaite has very generously tested this interactively, I think it's ready for review.

**Review by MarkEWaite — APPROVED** [review]
The change looks right to me.  I've tested interactively and confirmed that it is well-behaved in cases that were failing with the version in release 4.11.2.

**Comment by MarkEWaite** [comment]
I've run the automated tests on my RHEL-8, Windows, and other operating systems. Working well.

I plan to release a new version today

**Comment by MarkEWaite** [comment]
Release build has started for 4.11.3.  Releases from other branches will need a backport of the fixes.

**Comment by MarkEWaite** [comment]
Git plugin [4.11.3](https://github.com/jenkinsci/git-plugin/releases/tag/git-4.11.3) and [4.9.2](https://github.com/jenkinsci/git-plugin/releases/tag/git-4.9.2) have been released with this fix.  Thanks @dwnusbaum !

**Pull request merged**
