### PR TITLE
Stabilizing tests

### PR DESCRIPTION
**Pull request by jglick**
* Pick up https://github.com/jenkinsci/jenkins/pull/3428 in ATH builds to avoid timeouts.
* Avoid entropy-based timeouts in functional tests. (ported from #582)

### CODE REVIEW

**Comment by jglick** [comment]
https://github.com/jenkins-infra/pipeline-library/issues/58 would be beneficial but probably is not critical.

**Comment by jglick** [comment]
Ah, found something we _do_ need to fix, will file it.

**Comment by raul-arabaolaza** [comment]
The incrementals support for `runATH` and `runPCT` should work once [pipeline-library#58](https://github.com/jenkins-infra/pipeline-library/pull/58) [pipeline-library#59](https://github.com/jenkins-infra/pipeline-library/pull/59) and [pipeline-library#60](https://github.com/jenkins-infra/pipeline-library/pull/60) are merged, then we can rerun this PR to see if that fixes the problem, if not I have an already prepared PR to ATH increasing timeout that should fix the tests while we fix the root cause, see #588

**Comment by raul-arabaolaza** [comment]
All the changes in pipeline-library are merged, can anyone with permissions retrigger this PR?

**Comment by jglick** [comment]
@MarkEWaite so far as I am concerned, yes.

Note that the 4.x changes to bump up the baseline to 2.60.x (IIRC?) would obviate the need for the `sshd` override, but it seems useful to merge that to `master` in the interim.

**Pull request merged**
