### PR TITLE
[JENKINS-29603] Fix notifyCommit for branches that contain slashes

### PR DESCRIPTION
**Pull request by zonArt**
All credits go to @coder-hugo. This PR intends to fix the conflicts with master in order to get this useful fix to be merged
original PR is the following #369

### CODE REVIEW

**Comment by francoiscolombo** [comment]
+1 this is a good way to solve this problem.

**Comment by edomaur** [comment]
+1 well I hope it will be enough :-)

**Comment by pouete** [comment]
+1

**Comment by zonArt** [comment]
@MarkEWaite do you think this could be merged? I tried to solve the conflict by rebasing master on @coder-hugo initial pr

**Comment by zonArt** [comment]
Is it possible to see this PR being merged some days ? What do you propose to change or what's the best way to get initial issue solved ? Thanks in advance

**Comment by MarkEWaite** [comment]
It won't be merged very soon.  I am currently working on higher priority issues.

I am glad to see the "+1" comments since that indicates users are interested in the fix.  I'd prefer even more if users reported that they have compiled the change against the master branch and are running it successfully.

Changing the behavior of notifyCommit is especially sensitive, since mistakes in that area can cause many Jenkins installations to misbehave.

**Comment by pouete** [comment]
We are actually using these commits in our jenkins installation. 
So far, it is working.

**Comment by MarkEWaite** [comment]
I've started the evaluation of this pull request (finally, over a year after it was submitted).  As part of that review,

* resolved the trivial conflict with the master branch
* simplified the differences to the master branch (see my [dev branch](https://github.com/MarkEWaite/git-plugin/pull/16)), 
* created a [regression test job](https://github.com/MarkEWaite/docker-lfs/blob/lts-with-plugins/ref/jobs/Bugs-Individual/jobs/JENKINS-29603-notifyCommit-branch-with-slash-1/config.xml) which proved to me that I know how to duplicate the problem.
* included the regression test job in my [Pipeline regression tests](https://github.com/MarkEWaite/jenkins-bugs/tree/has-slash/JENKINS-29603)

I still need to spend some exploratory time looking for ways that this change might break compatibility with existing users.

**Comment by MarkEWaite** [comment]
Changes rebased and simplified in #592 .  Planned for inclusion in git plugin 4.0.0

**Pull request closed without merging**
