### PR TITLE
Remove powermock and sole test that used it

### PR DESCRIPTION
**Pull request by MarkEWaite**
Powermock creates problems in JDK 11 and has not helped the testing
and delivery of the plugin in any significant way.

## Remove powermock and the lone test that uses it

Already removed from the master branch for JDK 11 work.
Remove from the stable-3.9 branch because the test is not adding enough value to justify the JDK 11 disruption it causes.

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/jenkinsci/git-plugin/blob/master/CONTRIBUTING.md) doc
- [x] Unit tests pass locally with my changes
- [x] I have added documentation as necessary
- [x] No Javadoc warnings were introduced with my changes
- [x] No findbugs warnings were introduced with my changes
- [x] Any dependent changes have been merged and published in upstream modules (like git-client-plugin)

## Types of changes

- [x] Non-breaking change which fixes an issue with JDK 11

## Further comments

If this is a relatively large or complex change, start the discussion by explaining why you chose the solution you did and what alternatives you considered.

### CODE REVIEW

**Comment by MarkEWaite** [comment]
Wrong target branch.

**Comment by batmat** [comment]
You can change it by clicking on the edit button on the top Mark

**Comment by batmat** [comment]
Also would be very good to backport https://github.com/jenkinsci/git-plugin/pull/685 to the stable-3.9 branch

**Comment by MarkEWaite** [comment]
I'm not willing to backport #685 to stable-3.9.  That involves too many large changes for a branch that intentionally does not change the base Jenkins version.,

**Comment by MarkEWaite** [comment]
Superseded by #701

**Pull request closed without merging**
