### PR TITLE
Implemented JENKINS-37331 - Add branches to build list view column

### PR DESCRIPTION
**Pull request by MadsNielsen**
My first implemtation, any comments, reviews and changes to wordings would be appreciated.

### CODE REVIEW

**Comment by MadsNielsen** [comment]
@MarkEWaite Hi there, any chance this might get your review? I've got a customer that really wants this feature. Just let me know, if theres anything i need to do in order to expedite. Is this not something that you want in the Git plugin, if so, do you suggest making this a seperate plugin if it not something you want?

**Comment by MarkEWaite** [comment]
@MadsNielsen my focus has been on preparing the git plugin 2.6.0 release with support for branch indexing with command line git so that more authentication cases can be handled.  After that, my focus will shift to releasing git plugin 3.0 with support for submodule authentication.  I want to release submodule authentication in time for Jenkins world, since it is the most requested enhancement to the git plugin and it has been in beta for about a year.  My initial guess is that I won't be able to review your pull request until after mid-September.

Could you deliver a pre-release (preferably built from merging this pull request to the tip of the master branch) and have your customer report the results?  That would give me a second verification that your change is working, without requiring that I verify the pull request?

Alternately, could you have a person (other than you) in your company code review it and perform interactive testing of it so that increases my confidence it has been reviewed by two people?

**Comment by MadsNielsen** [comment]
@MarkEWaite I'll try to install a pre-built version for the customer. Let them try it out and let them provide feedback.

**Comment by MadsNielsen** [comment]
Hey @MarkEWaite i've installed the plugin at our customer a couple of weeks ago, and they've hadno incidents at all so far, is that good enough for you to accept this pull reqest?

**Comment by MadsNielsen** [comment]
Hey @MarkEWaite I rebased the original pull request ontop of the newest version of the Git plugin. The changes in this commit have been tested at the company for a couple of months now. 

Also. The change is very low risk since it's just an optional column you can add.

**Pull request merged**
