### PR TITLE
[JENKINS-50394] Get remote references before fetching to cache when discoverX

### PR DESCRIPTION
**Pull request by rsandell**
## [JENKINS-50394](https://issues.jenkins-ci.org/browse/JENKINS-50394) - Get remote references before fetching to local cache when discovering branches et.al.

This is the same as #702 cherry-picked and modified for the master/4.x branch.

## Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/jenkinsci/git-plugin/blob/master/CONTRIBUTING.md) doc
- [X] I have referenced the Jira issue related to my changes in one or more commit messages
- [X] I have added tests that verify my changes
- [X] Unit tests pass locally with my changes
- [X] I have added documentation as necessary
- [X] No Javadoc warnings were introduced with my changes
- [X] No spotbugs warnings were introduced with my changes
- [x] I have interactively tested my changes
- [x] Any dependent changes have been merged and published in upstream modules (like git-client-plugin)

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)

## Further comments

See https://github.com/jenkinsci/git-plugin/pull/702
Needs corresponding master release of git-client.

### CODE REVIEW

**Comment by rsandell** [comment]
Are the windows test failures something that happens normally?

> Caused by: jenkins.util.io.CompositeIOException: Unable to delete 'C:\Jenkins\workspace\Plugins_git-plugin_PR-706\target\jenkins-for-testx'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.

Looks very unrelated to my changes?

**Comment by MarkEWaite** [comment]
Windows tests do not generally fail, though it would be worth looking through the builds on the master branch to see if any of those failures are reported in the build history of the master branch

**Comment by rsandell** [comment]
Latest build of master all the windows tests fails with the same error

**Comment by rsandell** [comment]
I've been investigating why those windows tests are failing on the current master branch, but there is no significant change that I can see between the two versions that worked and suddenly didn't. And I don't have access to a windows machine to try and debug it on either. So I'm a bit lost.

**Comment by MarkEWaite** [comment]
No problem @rsandell , I'll double check that they are passing on my Windows infrastructure.  The ci.jenkins.io infrastructure has had issues recently.

**Comment by MarkEWaite** [comment]
Merged when #702 was merged to the master branch.  Thanks for letting me use this pull request for interactive testing!  It made my testing life simpler and let me complete the testing more quickly.

**Comment by rsandell** [comment]
@MarkEWaite Thanks!
Though this PR had slight changes to use more Java 8 features than #702 so they where not equivalent FYI.

**Comment by MarkEWaite** [comment]
Thanks for the note about the improvements in this PR @rsandell .  I'll merge the changes it provides.

**Comment by MarkEWaite** [comment]
Merged those changes.  Thanks

**Pull request closed without merging**
