### PR TITLE
[JENKINS-62261] Allow URL validation to accept custom TLDs

### PR DESCRIPTION
**Pull request by rishabhBudhouliya**
## [JENKINS-62261](https://issues.jenkins-ci.org/browse/JENKINS-62261) -Allow local domain names to be validated by the UrlValidator

The URL validation in the the repository browser settings was too strict and it treats e.g *.corp domains as invalid. To fix this, we have introduced the [DomainValidator](http://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/DomainValidator.html) with custom domain names (.corp, .local etc) to allow the possibility of validating urls with such custom local urls as well.

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/jenkinsci/git-plugin/blob/master/CONTRIBUTING.adoc) doc
- [x] I have referenced the Jira issue related to my changes in one or more commit messages
- [x] I have added tests that verify my changes
- [x] Unit tests pass locally with my changes
- [x] I have added documentation as necessary
- [x] No Javadoc warnings were introduced with my changes
- [x] No spotbugs warnings were introduced with my changes
- [ ] I have interactively tested my changes

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

## Further comments

This is a continuation on the great work done in https://github.com/jenkinsci/git-plugin/pull/890 by @sratz and @MarkEWaite .

### CODE REVIEW

**Comment by rishabhBudhouliya** [comment]
@sratz @MarkEWaite if we wish to continue the development in PR#890 itself, I can close this PR, we can take whatever necessary and add it to 890.

**Comment by MarkEWaite** [comment]
I'm fine with closing #890 since you've invested the effort to create this pull request.  However, this pull request seems to mix changes from other pull requests along with the proposed change for URL validation.  Can you rework this pull request to limit it to only URL validation?

**Comment by rishabhBudhouliya** [comment]
@MarkEWaite We now have the three commits related to JENKINS-62261.

**Comment by MarkEWaite** [comment]
Passed my interactive testing and code review.

**Review by MarkEWaite — COMMENTED** [review]
Approved

**Pull request merged**
