### PR TITLE
Enable testing with Java 11 on recommended configuration

### PR DESCRIPTION
**Pull request by oleg-nenashev**
## [JENKINS-xxxxx](https://issues.jenkins-ci.org/browse/JENKINS-xxxxx) - summarize pull request in one line

Describe the big picture of your changes here to explain to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, include a link to the issue.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/jenkinsci/git-plugin/blob/master/CONTRIBUTING.md) doc
- [ ] I have referenced the Jira issue related to my changes in one or more commit messages
- [ ] I have added tests that verify my changes
- [ ] Unit tests pass locally with my changes
- [ ] I have added documentation as necessary
- [ ] No Javadoc warnings were introduced with my changes
- [ ] No findbugs warnings were introduced with my changes
- [ ] I have interactively tested my changes
- [ ] Any dependent changes have been merged and published in upstream modules (like git-client-plugin)

## Types of changes

What types of changes does your code introduce? _Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Further comments

If this is a relatively large or complex change, start the discussion by explaining why you chose the solution you did and what alternatives you considered.

### CODE REVIEW

**Comment by batmat** [comment]
image

i.e.

`[ERROR] Tests run: 3885, Failures: 13, Errors: 2, Skipped: 2, Flakes: 1`

Many failures on JDK11 are expected and related to `workflow-support:3.x` (see #684) missing update:

```
Started
[Pipeline] node
[Pipeline] End of Pipeline
java.lang.NoClassDefFoundError: Could not initialize class org.jboss.marshalling.river.RiverMarshaller
	at org.jboss.marshalling.river.RiverMarshallerFactory.createMarshaller(RiverMarshallerFactory.java:54)
	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverWriter.<init>(RiverWriter.java:134)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:456)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:434)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgramIfPossible(CpsThreadGroup.java:422)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:362)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:82)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:242)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:230)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Finished: FAILURE
```

**Comment by oleg-nenashev** [comment]
Will merge #684 here

**Comment by oleg-nenashev** [comment]
@batmat 

```
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.

[ERROR] /home/jenkins/workspace/Plugins_git-plugin_java11-tests/src/main/java/hudson/plugins/git/util/InverseBuildChooser.java:20: error: tag not supported in the generated HTML version: tt

[ERROR]  * e.g. If <tt>&#x2a;&#x2a;/master</tt> and <tt>&#x2a;&#x2a;/release-&#x2a;</tt> are configured as

```

:(

**Comment by batmat** [comment]
OK, now apparently there are left failures, but they are real Javadoc issues, introduced IIRC by the javadoc tool having been made more picky after Java 8. I will see to fix these. We're still moving forward, that's great.

Thanks a lot Oleg!

**Comment by batmat** [comment]
Looking not that bad in the end:

```
[ERROR] Tests run: 3885, Failures: 0, Errors: 2, Skipped: 2, Flakes: 1
[INFO] 
[ERROR] There are test failures.

Please refer to /mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[INFO] 
[INFO] --- maven-license-plugin:1.7:process (default) @ git ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1 (file:/mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests@tmp/m2repo/org/codehaus/groovy/groovy/1.6.5/groovy-1.6.5.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass$3$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Generated /mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/target/git/WEB-INF/licenses.xml
[INFO] 
[INFO] --- maven-hpi-plugin:3.3:hpi (default-hpi) @ git ---
[INFO] Generating /mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/target/git/META-INF/MANIFEST.MF
[INFO] Checking for attached .jar artifact ...
[INFO] Generating jar /mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/target/git.jar
[INFO] Building jar: /mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/target/git.jar
[INFO] Exploding webapp...
[INFO] Copy webapp webResources to /mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/target/git
[INFO] Assembling webapp git in /mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/target/git
[INFO] Generating hpi /mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/target/git.hpi
[INFO] Building jar: /mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/target/git.hpi
[INFO] 
[INFO] --- maven-jar-plugin:3.1.1:test-jar (maybe-test-jar) @ git ---
[INFO] Building jar: /mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/target/git-tests.jar
[INFO] 
[INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ git ---
[INFO] Building jar: /mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/target/git-sources.jar
[INFO] 
[INFO] --- maven-source-plugin:3.0.1:test-jar-no-fork (attach-test-sources) @ git ---
[INFO] Building jar: /mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/target/git-test-sources.jar
[INFO] 
[INFO] --- maven-javadoc-plugin:3.0.1:jar (attach-javadocs) @ git ---
[INFO] 
5 errors
1 warning
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:19 min
[INFO] Finished at: 2019-03-08T16:28:45Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (attach-javadocs) on project git: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - /mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/src/main/java/hudson/plugins/git/util/InverseBuildChooser.java:20: error: tag not supported in the generated HTML version: tt
[ERROR]  * e.g. If <tt>&#x2a;&#x2a;/master</tt> and <tt>&#x2a;&#x2a;/release-&#x2a;</tt> are configured as
[ERROR]            ^
[ERROR] /mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/src/main/java/hudson/plugins/git/util/InverseBuildChooser.java:20: error: tag not supported in the generated HTML version: tt
[ERROR]  * e.g. If <tt>&#x2a;&#x2a;/master</tt> and <tt>&#x2a;&#x2a;/release-&#x2a;</tt> are configured as
[ERROR]                                             ^
[ERROR] /mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/src/main/java/hudson/plugins/git/util/InverseBuildChooser.java:24: error: tag not supported in the generated HTML version: tt
[ERROR]  * This is useful, for example, when you have jobs building your <tt>master</tt> and various
[ERROR]                                                                  ^
[ERROR] /mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/src/main/java/hudson/plugins/git/util/InverseBuildChooser.java:25: error: tag not supported in the generated HTML version: tt
[ERROR]  * <tt>release</tt> branches and you want a second job which builds all new feature branches &mdash;
[ERROR]    ^
[ERROR] /mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/src/main/java/hudson/plugins/git/util/InverseBuildChooser.java:27: error: tag not supported in the generated HTML version: tt
[ERROR]  * <tt>master</tt> and the release branches again each time they change.
[ERROR]    ^
[ERROR] /mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/src/main/java/hudson/plugins/git/util/BuildChooser.java:190: warning: @return has already been specified
[ERROR]      * @return
[ERROR]        ^
[ERROR] 
[ERROR] Command line was: /mnt/agent-workspace/tools/hudson.model.JDK/jdk11/jdk-11.0.2/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/target/apidocs' dir.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (attach-javadocs) on project git: MavenReportException: Error while generating Javadoc: 
Exit code: 1 - /mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/src/main/java/hudson/plugins/git/util/InverseBuildChooser.java:20: error: tag not supported in the generated HTML version: tt
 * e.g. If <tt>&#x2a;&#x2a;/master</tt> and <tt>&#x2a;&#x2a;/release-&#x2a;</tt> are configured as
           ^
/mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/src/main/java/hudson/plugins/git/util/InverseBuildChooser.java:20: error: tag not supported in the generated HTML version: tt
 * e.g. If <tt>&#x2a;&#x2a;/master</tt> and <tt>&#x2a;&#x2a;/release-&#x2a;</tt> are configured as
                                            ^
/mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/src/main/java/hudson/plugins/git/util/InverseBuildChooser.java:24: error: tag not supported in the generated HTML version: tt
 * This is useful, for example, when you have jobs building your <tt>master</tt> and various
                                                                 ^
/mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/src/main/java/hudson/plugins/git/util/InverseBuildChooser.java:25: error: tag not supported in the generated HTML version: tt
 * <tt>release</tt> branches and you want a second job which builds all new feature branches &mdash;
   ^
/mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/src/main/java/hudson/plugins/git/util/InverseBuildChooser.java:27: error: tag not supported in the generated HTML version: tt
 * <tt>master</tt> and the release branches again each time they change.
   ^
/mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/src/main/java/hudson/plugins/git/util/BuildChooser.java:190: warning: @return has already been specified
     * @return
       ^

Command line was: /mnt/agent-workspace/tools/hudson.model.JDK/jdk11/jdk-11.0.2/bin/javadoc @options @packages

Refer to the generated Javadoc files in '/mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/target/apidocs' dir.

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: MavenReportException: Error while generating Javadoc: 
Exit code: 1 - /mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/src/main/java/hudson/plugins/git/util/InverseBuildChooser.java:20: error: tag not supported in the generated HTML version: tt
 * e.g. If <tt>&#x2a;&#x2a;/master</tt> and <tt>&#x2a;&#x2a;/release-&#x2a;</tt> are configured as
           ^
/mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/src/main/java/hudson/plugins/git/util/InverseBuildChooser.java:20: error: tag not supported in the generated HTML version: tt
 * e.g. If <tt>&#x2a;&#x2a;/master</tt> and <tt>&#x2a;&#x2a;/release-&#x2a;</tt> are configured as
                                            ^
/mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/src/main/java/hudson/plugins/git/util/InverseBuildChooser.java:24: error: tag not supported in the generated HTML version: tt
 * This is useful, for example, when you have jobs building your <tt>master</tt> and various
                                                                 ^
/mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/src/main/java/hudson/plugins/git/util/InverseBuildChooser.java:25: error: tag not supported in the generated HTML version: tt
 * <tt>release</tt> branches and you want a second job which builds all new feature branches &mdash;
   ^
/mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/src/main/java/hudson/plugins/git/util/InverseBuildChooser.java:27: error: tag not supported in the generated HTML version: tt
 * <tt>master</tt> and the release branches again each time they change.
   ^
/mnt/agent-workspace/workspace/Plugins_git-plugin_java11-tests/src/main/java/hudson/plugins/git/util/BuildChooser.java:190: warning: @return has already been specified
     * @return
       ^

Command line was: /mnt/agent-workspace/tools/hudson.model.JDK/jdk11/jdk-11.0.2/bin/javadoc @options @packages
```

**Comment by batmat** [comment]
@oleg-nenashev https://github.com/jenkinsci/git-plugin/pull/688 should fix the Javadoc failure. If you can cherry-pick it here, that'd be great. Maybe we'd then even get a green build here :-).

Thanks!

**Pull request merged**
