### PR TITLE
Fix PCT for 2.32.2

### PR DESCRIPTION
**Pull request by varyvol**
Include test dependencies to fix PCT for Jenkins 2.32.2 (running tests with jenkins.version=2.32.2).

Also specify the project will use a parameter.

@reviewbybees @MarkEWaite

### CODE REVIEW

**Comment by MarkEWaite** [comment]
Could someone expand the acronym "PCT" for me?  I have no objection to these changes, and will happily merge them, but I don't understand why they are needed or the testing use case which will benefit from them.

**Comment by jglick** [comment]
[`plugin-compat-tester`](https://github.com/jenkinsci/plugin-compat-tester/)

@varyvol, @kwhetstone, etc., when filing these PRs for non-CloudBees maintainers you need to give a little background. These are needed to make tests pass when running something like

    mvn test-compile && mvn -Djenkins.version=2.32.2 surefire:test

plus in some cases updates of plugin dependencies as well. In this case you can see for yourself the problem:

```
Started by user SYSTEM
Building in workspace /tmp/jenkinsTests.tmp/jenkins…test/workspace/test0
Cloning the remote Git repository
Cloning repository /tmp/junit…/junit…
 > git init /tmp/jenkinsTests.tmp/jenkins…test/workspace/test0 # timeout=10
Fetching upstream changes from /tmp/junit…/junit…
 > git --version # timeout=10
 > git fetch --tags --progress /tmp/junit…/junit… +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url /tmp/junit…/junit… # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url /tmp/junit…/junit… # timeout=10
Fetching upstream changes from /tmp/junit…/junit…
 > git fetch --tags --progress /tmp/junit…/junit… +refs/heads/*:refs/remotes/origin/*
 > git rev-parse origin/${MY_BRANCH}^{commit} # timeout=10
 > git rev-parse ${MY_BRANCH}^{commit} # timeout=10
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
Finished: FAILURE
```

See `workflow-step-api-plugin/Jenkinsfile` for an example of how you can make your regular CI build verify the same thing.

**Comment by varyvol** [comment]
Thanks for the explanation @jglick Will take note of including the extra background for another occasions.

@MarkEWaite I hope that clarifies a little. Basically we execute that kind of command to validate the plugin works properly with such Jenkins version.

**Comment by MarkEWaite** [comment]
Thanks.  That was the explanation I needed.

**Pull request merged**
