### PR TITLE
AbstractGitSCMSource.getPattern bug

### PR DESCRIPTION
**Pull request by jglick**
[Tip](http://stackoverflow.com/a/2848147/12916)

#227 was translating `feature/*/private` to `\Qfeature/\E\Q/private\E` rather than `\Qfeature/\E.*\Q/private\E` as you would expect.

@reviewbybees esp. @Vlatombe

### CODE REVIEW

**Comment by jglick** [comment]
Could use a more standard glob implementation like `SelectorUtils` but for purposes of this PR I limited myself to fixing what looked like a clear bug.

**Comment by KostyaSha** [comment]
Please fill jira issue. I expect linked issues case.

**Comment by andresrc** [comment]
:bee:

**Comment by Vlatombe** [comment]
:bee:

**Comment by jglick** [comment]
@reviewbybees done

**Comment by KostyaSha** [comment]
👎 

> Please fill jira issue. I expect linked issues case.

**Comment by jglick** [comment]
If the plugin maintainer cares, I will create one.

**Pull request merged**
