### PR TITLE
Add images to improve docs clarity

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Add images to improve docs clarity

The images provide more context for the reader.  They help the reader confirm that the screen they are seeing in their running Jenkins instance is similar to the screen being documented.

Accepts that the conversion from tables to divs will justify revising all these screenshots, but that is not likely to arrive in an LTS for at least 3 months.

Review in context in the [pull request README](https://github.com/MarkEWaite/git-plugin/blob/add-images-to-docs/README.adoc) , compare with the [master branch README](https://github.com/jenkinsci/git-plugin/blob/master/README.adoc) and with the [plugins.jenkins.io version](https://plugins.jenkins.io/git/).

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/jenkinsci/git-plugin/blob/master/CONTRIBUTING.adoc) doc
- [x] I have referenced the Jira issue related to my changes in one or more commit messages
- [x] I have added documentation as necessary

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by MarkEWaite** [comment]
Would like review from at least one person, but will merge even without reviews in a few days.

**Comment by kshultzCB** [comment]
I'll be able to look on Monday morning. :)

**Comment by kshultzCB** [comment]
I actually missed my window by 19 seconds. But this LGTM. More screenshots are always great 👍

**Comment by MarkEWaite** [comment]
Thanks for reviewing it  @kshultzCB .

Next stop, the pipeline symbols work and then a beta release by end of this week.  We're less than two weeks away from the release of 2.235.1.

**Pull request merged**
