### PR TITLE
[JENKINS-42487] Exclude git repository from being polled for changes.

### PR DESCRIPTION
**Pull request by per-bohlin**
https://issues.jenkins-ci.org/browse/JENKINS-42487
See above issue for additional information.

### CODE REVIEW

**Comment by zen-devconsoft** [comment]
The tests seem to fail due to misconfiguration of git on the windows build nodes.

```
 > git.exe tag -a -f -m Jenkins Build #1 jenkins-test0-1-SUCCESS # timeout=10
ERROR: Failed to push merge to origin repository
hudson.plugins.git.GitException: Could not apply tag jenkins-test0-1-SUCCESS
 at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.tag(CliGitAPIImpl.java:1367)
 at hudson.plugins.git.GitAPI.tag(GitAPI.java:274)
 at hudson.plugins.git.GitPublisher.perform(GitPublisher.java:215)
 at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
 at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:785)
 at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
 at hudson.model.Build$BuildExecution.post2(Build.java:185)
 at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
 at hudson.model.Run.execute(Run.java:1766)
 at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
 at hudson.model.ResourceController.execute(ResourceController.java:98)
 at hudson.model.Executor.run(Executor.java:408)
Caused by: hudson.plugins.git.GitException: Command "git.exe tag -a -f -m Jenkins Build #1 jenkins-test0-1-SUCCESS" returned status code 128:
stdout: 
stderr: 
*** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: empty ident name (for <(null)>) not allowed

```

**Comment by zen-devconsoft** [comment]
Also, it is unfortunate that the old jenkins build is still triggered by github since it can never complete due to being disabled.

**Comment by per-bohlin** [comment]
Rebased on current HEAD of master (f2b45cbdc23f7cc5061bb00df2b751519c0a0ead)
 
The failed tests are due to problems already on master as far as I can tell and not caused by this change.

**Comment by MarkEWaite** [comment]
Isn't this capability already available from the checkbox "Ignore post-commit hooks" in the "Poll SCM" definition at the job level?  I confirmed that it worked as expected for the "whole job" case.

The [bug report](https://issues.jenkins-ci.org/browse/JENKINS-42487) describes controlling polling for individual repositories within multi-SCM as a use case, but (for me at least), I'd much rather not add this feature to the plugin for multi-SCM support when I'm not sure how it will interact with Pipeline.  Will users expect that Pipeline will ignore post-commit hooks when they set this additional behavior?

I'd like a discussion of this with @jglick and @abayer based on the direction they are taking with Pipeline.

**Comment by per-bohlin** [comment]
@MarkEWaite, thanks for checking in on this pull request and providing feedback.

Ideally, I would have liked to implement it as a pure git-extension and deploy it as a completely separate plugin. However, due to the git-plugin's extension interface that was not possible.
Our scenario covered the execution path without workspace, bypassing the whole extension mechanism, hence the current solution.
Our main scenario is indeed multi-SCM where we want to use the scmNotify mechanism to trigger builds based on changes in some of the repositories used by the job, but not changes in other repositories.
We don't have any other work-around available to use, so if this does not end up in the official version we will have to keep maintaining our alternative version, or hope for a change in the extension interface in the future that allows for extensions that act on the "no workspace" scenario.

**Comment by jglick** [comment]
> we want to use the scmNotify mechanism to trigger builds based on changes in some of the repositories used by the job, but not changes in other repositories

This is already supported natively by Pipeline.

**Pull request closed without merging**
