### PR TITLE
[WIP] fix JENKINS-28506 - refs/heads/ based polling worked in 2.3.4, broke in 2.3.5

### PR DESCRIPTION
**Pull request by MarkEWaite**
This is a *work in progress*, not a ready to merge pull request.  I'm leaving on vacation for a week plus and wanted to share the results in case someone else begins investigating the problem

I created several new tests of refs/head based branches on a branch based off the git-2.3.4 tag. Once I confirmed the tests were passing and reasonable on that branch, I merged various subtrees of the changes between git-2.3.4 and git-2.3.5 and ran tests on those test merges.

The tests showed that 85463e98eb410081222792b4d899c71cfbf42e9 was the commit which changed refs/heads behaviors compared to 2.3.4.

Reverting the GitSCM changes from that commit passed the trigger (polling) tests which had been failing prior to the revert.

GitSCMTest.testPollingAfterManualBuildWithParametrizedBranchSpec is the one test which is failing in this pull request. Even if this is the right approach, this should not be merged until that test failure is understood and the code is corrected so that it passes.

@ndeloof can you review this, and possibly consider if @reviewByBees is justified?  I would like to fix the open issues inserted into 2.3.5 and then release a new version of the git plugin and the git client plugin in late June or early July).

### CODE REVIEW

**Comment by ndeloof** [comment]
wouldn't it be simpler to just discard support for `refs/heads` syntax and only do support branch name in BranchSpec ? git-plugin is so "flexible" (sic) for legacy reasons its mostly impossible for it to evolve

**Comment by KostyaSha** [comment]
@ndeloof how you will access `refs/notes` `refs/tags` and any other namespaces?

**Comment by ndeloof** [comment]
most users just do use `origin/branch` or just `branch` - this works as well with tags
I agree the `refs/*` syntax is stricter, but might not be necessary but for very exotic usages.

I'm looking into this same issue in the meantime

**Comment by ndeloof** [comment]
I cherry-picked you test case an proposed an alternate fix https://github.com/jenkinsci/git-plugin/pull/324

**Comment by MarkEWaite** [comment]
@ndeloof has a better solution in pull request 324. Closing this incomplete pull request

**Pull request closed without merging**
