### PR TITLE
[JENKINS-34350] Fix POST to /git/notifyCommit with CSRF protection on

### PR DESCRIPTION
**Pull request by liskin**

### CODE REVIEW

**Comment by MarkEWaite** [comment]
I created an [integration test](https://github.com/MarkEWaite/jenkins-bugs/tree/JENKINS-34350) to confirm I could see the failure when a POST to /git/notifyCommit with CSRF enabled, and I've confirmed that this change resolves the failure.

**Comment by liskin** [comment]
Oh, I was just about to submit a unit test I've been writing all day. :-)

**Comment by MarkEWaite** [comment]
Please submit the unit test.  Unit tests are much better (for the developers) than integration tests.

**Comment by liskin** [comment]
Pushed. Please do note that this is my first experience with Jenkins codebase, Java unit tests in general and maven, so it might not be up to standards. Also I just noticed that my files use tabs instead of spaces. I should probably amend that.

**Pull request merged**
