### PR TITLE
[JENKINS-43894] Resolve environment variables in CloneOption reference path

### PR DESCRIPTION
**Pull request by atikhono**
## JENKINS-43894 - Resolve environment variables in CloneOption reference path

https://issues.jenkins-ci.org/browse/JENKINS-43894
On contrary to Freestyle projects' `getEnvironment`, `WorkflowRun.getEnvironment` doesn't provide node-specific environment variables as it can have multiple `node` blocks in parallel (see https://issues.jenkins-ci.org/browse/JENKINS-36267). So I suggest to pick up envvars just in place. @MarkEWaite @jglick 

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/jenkinsci/git-plugin/blob/master/CONTRIBUTING.md) doc
- [x] I have referenced the Jira issue related to my changes in one or more commit messages
- [ ] I have added tests that verify my changes
- [x] Unit tests pass locally with my changes
- [ ] I have added documentation as necessary
- [ ] No Javadoc warnings were introduced with my changes
- [x] No findbugs warnings were introduced with my changes
- [x] I have interactively tested my changes
- [ ] Any dependent changes have been merged and published in upstream modules (like git-client-plugin)

## Types of changes

What types of changes does your code introduce?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by atikhono** [comment]
@MarkEWaite could you please have a look?

**Comment by tarioch** [comment]
@atikhono Could you provide the hpi file with the patch applied? Still having some issues with our other workaround and I think would be easier to simply use the patched version, still hoping this will get reintegrated soon

**Comment by atikhono** [comment]
@tarioch you can just pull it and build with maven: mvn package -DskipTests. The resulting hip will be in target/git.hpi.

**Comment by MarkEWaite** [comment]
@tarioch you can also [download the hpi file](https://ci.jenkins.io/job/Plugins/job/git-plugin/job/PR-575/3/artifact/target/git.hpi) as an artifact of the automated checks.

**Comment by tarioch** [comment]
Can confirm works fine for me as well

**Comment by tarioch** [comment]
Just found a not so nice limitation/problem which would be nice to get fixed as well.

Following situation:
* path on master /foo/reference
* path on slave /bar/reference

What I now see is that when it's doing the checkout for retrieving the Jenkinsfile on the master, it's already trying to use /bar/reference but it should use /foo/reference and only in the actual pipeline code it should use /bar/reference.

**Comment by tarioch** [comment]
Tried to figure out more but I'm not able to figure out what goes wrong.

== Test 1: Job which runs on slave ==
On master when checking out
....myjob@script
It tries to use the path as specified on the slave and prints out
Error reference path does not exist: /path/on/slave

When it then gets to the Slave and does the checkout there, it correctly uses /path/on/slave

== Test 2: Job which runs master ==
On master when checking out
...myjob2@script
It uses correctly /path/on/master

**Comment by tarioch** [comment]
Hmm, strange cleaned out job workspace and now it worked, could this be some race condition?

**Comment by tarioch** [comment]
Starting to wonder if something was messed up, right now no longer able to reproduce it.

**Comment by atikhono** [comment]
@tarioch git won’t add a reference to an existing workspace because reference is added at clone. You should remove all existing workspaces to make it work.

**Comment by tarioch** [comment]
@atikhono it was new workspaces but it could be that there was still something from my workaround I had used earlier lying around, now haven't been able to reproduce it and seems to work fine.

**Comment by tarioch** [comment]
@MarkEWaite  any chance of getting this merged?

**Comment by tarioch** [comment]
@MarkEWaite Anything we can do to get this merged?

**Comment by mikebro** [comment]
Will this PR work in a scenario where you have Linux and Windows agents? If so, could you provide an example of how to reference the environment variable? Would it be for example `${PathToReferenceRepo}`, `%PathToReferenceRepo%`? I upgraded to v4 beta 8 and it didn't seem to work but I had to downgrade quickly because it was breaking our build process (same issue as [here](https://issues.jenkins-ci.org/browse/JENKINS-55939?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel)). This change would be great for us and save a decent amount of time building PRs so I would like to go back and test it again.

Our specific case is our master is Linux and the slaves are Windows, multi-branch pipeline for PRs have to [clone the entire repo on the master to obtain the Jenkinsfile](https://support.cloudbees.com/hc/en-us/articles/115002991272-Why-is-my-multibranch-project-cloning-the-whole-repository-on-the-master-), then of course clone it again on the slave, so we have to choose if we want the master or slaves to have a reference repo set up.

**Comment by MarkEWaite** [comment]
@mikefero it should work on Windows and Linux agents.  The environment variable would be referenced as `${PathToReferenceRepo}`.  Variable references inside Jenkins use the shell style syntax rather than batch style syntax for references. 

Multi-branch Pipelines can also be aggressively tuned to use a narrow refspec to clone less of the repository (assuming the repository contains many branches).  Refer to examples in my jenkins-bugs repository for samples that use checkout with a narrow refspec to accelerate checkout.

**Comment by tarioch** [comment]
Works perfectly fine for both Windows and Linux agents, we're actually using this for more than a year.

**Comment by mikebro** [comment]
@tarioch @MarkEWaite Excellent, thank you for the info & quick responses.

**Pull request merged**
