### PR TITLE
[JENKINS-35687] Add simple git lfs support

### PR DESCRIPTION
**Pull request by creste**
This is a refactoring of @matthauck's changes from jenkinsci/git-plugin#414.  This PR depends on jenkinsci/git-client-plugin#232, which explains the changes in more detail.

### CODE REVIEW

**Comment by newsoulbr** [comment]
I add this code on my local repository based on master and installed in my environment and it worked fine, no issues at this moment. Definitely fixed my problem with Git LFS

**Comment by baffles** [comment]
FWIW, I've built the modified plugin and it seems to be working fine for me (we needed LFS support within Jenkins).

**Comment by johnwbyrd** [comment]
Hey baffles, what is your take on the failed checks?

**Comment by MarkEWaite** [comment]
The LFS support in the git-plugin depends on LFS related changes in the git-client-plugin.  Since the job on ci.jenkins.io does not have a published copy (even snapshot) of the necessary git-client-plugin changes, it can't build (or test) the changes in the git plugin.

I believe that recent changes to artifactory repository permissions may now allow anyone to push a snapshot build to the jenkins artifactory, so it may be possible to resolve that.  However, I don't think that is actually very much help to the pull request evaluation process.

When I start evaluating this pull request in detail, I'll run the automated tests on many different platforms (Windows, Red Hat 6, Red Hat 7, Debian 7, Debian 8, Ubuntu 14, Ubuntu 16, possibly others) and will run interactive tests using those same platforms.  The automated tests on ci.jenkins.io are nice to have, but in this particular case, they are a small portion of the total work to evaluate the pull request.

**Comment by MarkEWaite** [comment]
I've added an [unauthenticated verification job](https://github.com/MarkEWaite/docker/commit/ea220761a2ad8134428d54f59d0a69c3853b5837) to my [lts-with-plugins docker repository](https://github.com/MarkEWaite/docker/tree/lts-with-plugins). That job passes with [git client plugin PR232](https://github.com/jenkinsci/git-client-plugin/pull/232) and this pull request.

I've added an authenticated verification job to my private docker repo. That job passes with [git client plugin PR232](https://github.com/jenkinsci/git-client-plugin/pull/232) and this pull request.

I've added an authenticated verification job with Jenkins pipeline and it fails to checkout with an error. I'll need to investigate further to understand the failure.

**Comment by creste** [comment]
I have successfully been using #463 in a test environment with pipeline builds for a while now.  It looks like the error you are getting is caused by an authentication error with GitHub.  I suspect either invalid or no credentials have been specified.

In my Multibranch Pipeline configuration I had to configure the credentials to use for Git on the web UI.   I'm using public+private key authentication with my git server (not GitHub).  In my pipeline script, I'm using the following code to clone the repository:

```groovy
        checkout([
                $class: 'GitSCM',
                branches: scm.branches,
                browser: scm.browser,
                doGenerateSubmoduleConfigurations: scm.doGenerateSubmoduleConfigurations,
                extensions: scm.extensions + [
                        [ $class: 'GitLFSPull' ]
                ],
                submoduleCfg: scm.submoduleCfg,
                userRemoteConfigs: scm.userRemoteConfigs
        ])
```

I purposefully added the `GitLFSPull` extension in the pipeline script because I only want to pull large files under certain circumstances.  The above command inherits the credentials configured in the UI so that I don't have to specify credentials in the pipeline script.

As you can see in [CliGitAPIImpl.java](https://github.com/jenkinsci/git-client-plugin/pull/232/files#diff-4a13310f7c84a9d6e133def48c0aed5aR2068), the `git lfs pull` command is being executed with the same credentials used for the `git checkout` command.  If one works then the other one should work too, assuming the LFS remote is the same as the checkout remote.  Although the remotes should be the same in all cases I can think of, if they were different then you have to make sure the same private key is trusted in both remotes.

Here are some ideas I have for troubleshooting the problem:
  * Check to see how many remotes are configured in the repository and what their URLs are
  * Try to manually run git lfs pull from the same repository and environment that Jenkins is running in.
  * Add `GIT_TRACE=1` before calls to git to see what SSH command it being executed.  You can then manually run the SSH command with `-vvv` to see which authentication methods and private key(s) are being used.
  * Try to locate the temporary file where Jenkins stores the private key during checkout and make sure it is the correct private key.
  * If your private key is password protected them make sure the password is correct.

**Comment by MarkEWaite** [comment]
Thanks for the suggestions.  I had configured the GitLFSPull class in the Jenkinsfile on the repository branch, but had failed to add it to the parent job definition in Jenkins.  The setting was read from GitHub as expected, but the parent repository where the Jenkinsfile is extracted did not include the LFS extension, so was failing the checkout.

Once I added it to the parent job definition, the job ran successfully.

I think that means there are many different use cases to be evaluated, like:
- LFS in a multi-configuration job across multiple platforms and git versions (already evaluated)
- LFS with multi-branch pipeline (with LFS enabled in the job definition - my failure case)
- LFS in a single pipeline job (confirm pipeline syntax shows correctly, etc.)
- LFS in one branch of a repository, but not in a different branch (already being tested)
- LFS with JGit (there are some hints it might work)

I don't think we need to resolve all those use cases, but I'd like to explore and understand them better before including the changes in a plugin release.

I also want to perform integration tests based on [JENKINS-30318](https://issues.jenkins-ci.org/browse/JENKINS-30318), [JENKINS-35687](https://issues.jenkins-ci.org/browse/JENKINS-35687), [JENKINS-38708](https://issues.jenkins-ci.org/browse/JENKINS-38708), and [JENKINS-40174](https://issues.jenkins-ci.org/browse/JENKINS-40174).

**Comment by creste** [comment]
I'm glad to hear you resolved the issue!  Please let me know if there is anything you'd like me do to assist with evaluating the other use cases.

**Comment by erebel55** [comment]
What is keeping this from being merged? The PR is pretty tiny, seems like important functionality to me. I'm having to copy over files manually after jenkins build has started, since it can't fetch the lfs files correctly.

**Comment by jhoblitt** [comment]
@erebel55 It depends on changes in another plugin and LFS is difficult to test.  https://github.com/jenkinsci/git-client-plugin/pull/232/files

**Comment by MarkEWaite** [comment]
I'd certainly like to have additional help testing the proposed changes.  You can download the [git client plugin](https://github.com/MarkEWaite/docker/blob/50c2c1c67232462cb1f7a5e75bd73d3611e6be9b/ref/plugins/git-client.jpi) and the [git plugin](https://github.com/MarkEWaite/docker/blob/50c2c1c67232462cb1f7a5e75bd73d3611e6be9b/ref/plugins/git.jpi) from the lts-with-plugins branch of my docker instance.  

I deeply appreciate comments on pull requests which say "I've installed this plugin and am using it successfully".  I also deeply appreciate comments which indicate when a problem has been encountered.  

With over 80 000 installations of the git plugin and git client plugin, I like to be careful about changes, especially additions of significant new capability (like large file support).

**Comment by gilramir** [comment]
I'm currently using the plugins and it's working for me.

**Comment by thetaiter** [comment]
For some reason the first pull does not work with the plugin. No matter how much time I allow for checkout by increasing the timeout, It waits forever and eventually times out. I have to go to the machine and manually pull with "git lfs clone <repo>", after that, the plugin works fine.

**Comment by MarkEWaite** [comment]
@thetaiter, any chance you're using a non-default location as the source of your large files?  The current implementation assumes that the large files are coming from the default source.

**Comment by thetaiter** [comment]
@MarkEWaite If you are referring to the Endpoint URL that I see what I run `git lfs env`, I believe that is the default location. We have not changed it. The repo as well as this Endpoint URL are on a private GHE server. The Endpoint URL is `https://<GHE_URL>/<organization>/<repo>.git/info/lfs`.

**Pull request merged**
