### PR TITLE
git: throw IOException around submodule update failures

### PR DESCRIPTION
**Pull request by jacob-keller**
Since these commands can fail due to the same reason as git checkout,
(too many concurrent accesses to the git server, for example), we need
to throw an exception caught by the retry loop. Based on inspection, it
appears that the best choice to catch is GitException, since that's what
is thrown by the launchCommand flow that calls the git submodule
command.

Signed-off-by: Jacob Keller jacob.e.keller@intel.com

### CODE REVIEW

**Comment by KostyaSha** [comment]
I don't think that this error message is exact.

**Comment by jacob-keller** [comment]
Do you have a better suggestion? The particular issue I am trying to solve is: 

 > git submodule update --remote src/COMPAT
FATAL: Command "git submodule update --remote src/COMPAT" returned status code 1:
stdout: 
stderr: ssh_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Unable to fetch in submodule path 'src/COMPAT'

hudson.plugins.git.GitException: Command "git submodule update --remote src/COMPAT" returned status code 1:
stdout: 
stderr: ssh_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Unable to fetch in submodule path 'src/COMPAT'

This can be fixed if we perform a retry, since it occurs only due to too many concurrent connections.

Since we're wrapping submodule update command I figured that it would be best to say we couldn't perform the submodule update here.. Maybe a better wording would be something like "Failed git submodule update"?

**Comment by KostyaSha** [comment]
Is it possible to parse error message and retry it when it matches some keywords?

**Comment by jacob-keller** [comment]
I really wouldn't want to go that route. We do the same thing for a normal git-clone or git-fetch to throw an IO exception, and I think it's safe to do here, we'll only retry up to the retry limit before giving up.

See line 1137 in checkout Command.

I don't know if there is a better exception to throw in some cases, but that would require changes to the git client plugin as well, which I would prefer avoiding.

**Comment by jacob-keller** [comment]
We could instead make a single change to git-client-plugin which will change to throw IOException under some circumstances, I will investigate that route.

**Comment by jacob-keller** [comment]
Ok so there is some precedent for checking specific messages and throwing a different exception.

I am not sure what the most ideal thing to check for would be, though.

**Comment by KostyaSha** [comment]
It's only question, please wait other opinions.

**Comment by jacob-keller** [comment]
> It's only question, please wait other opinions.

Yep, I'm just thinking out loud in a sense.

Thanks,
Jake

**Pull request closed without merging**
