### PR TITLE
Init Org/Repo Name regex 

### PR DESCRIPTION
**Pull request by Hrushi20**
## [JENKINS-54868](https://issues.jenkins.io/browse/JENKINS-54868) - Adds Organization/Project and Repository name

Added a global git config for regex which is used internally to get the project name and repo name.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is simply a reminder of what we are going to look for before merging your code. If a checkbox or line does not apply to this pull request, delete it. We prefer all checkboxes to be checked before a pull request is merged_

- [x] I have read the [CONTRIBUTING](https://github.com/jenkinsci/git-plugin/blob/master/CONTRIBUTING.adoc) doc
- [ ] I have referenced the Jira issue related to my changes in one or more commit messages
- [ ] I have added tests that verify my changes
- [x] Unit tests pass locally with my changes
- [] I have added documentation as necessary
- [x] No Javadoc warnings were introduced with my changes
- [x] No spotbugs warnings were introduced with my changes
- [ ] Documentation in README has been updated as necessary
- [] Online help has been added and reviewed for any new or modified fields
- [ ] I have interactively tested my changes
- [] Any dependent changes have been merged and published in upstream modules (like git-client-plugin)

## Types of changes

What types of changes does your code introduce? _Put an `x` in the boxes that apply. Delete the items in the list that do *not* apply_

- [ ] Dependency or infrastructure update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by Hrushi20** [comment]
I have not added any tests because it is not the finalized version. I'll add the tests once everything is implemented.

**Comment by Hrushi20** [comment]
I'll add the test cases. Is the implementation as expected?

**Comment by krisstern** [comment]
It is better to add the tests to find out. Otherwise this PR cannot be reviewed.

**Comment by Hrushi20** [comment]
Sure. I'll add the test cases👍👍👍
Thank You

**Comment by Hrushi20** [comment]
Hey @krisstern! I didn't know I could reopen a PR. I created another pull request by mistake. Do I close this PR or that one.

**Comment by krisstern** [comment]
@Hrushi20 No worries, I didn't realise you opened a new issue since you have not referenced it here. Let's continue our work over #1228  instead. We should retain only one branch to avoid confusion. Let's close this issue definitively. Remember to delete the branches you do not need anymore both locally and on GitHub.

**Pull request closed without merging**
