### PR TITLE
Fixed multibranch polling with exclusions

### PR DESCRIPTION
**Pull request by pbaranchikov**
Incorrect behavior is detected when the job has excluded paths and is aimed to track multiple branches. Consider the following:
<pre>
master: 1+ ---- 3+ -- 4
branch1:   \-2+ --------- 5
</pre>
Commits suffixed with "+" are commits with some paths that are not excluded, so the build should trigger for them only. Number of commit shows the time it is committed.
In this situation commit 5 causes project build, while 5 is to be ignored.

The cause of the error is that Git plugin uses last build information to get all the new commits to analyze. After commit 5 is pushed, Git plugin checks for the latest build (it is for commit 3) and try to get all the new commits as git log 3..5, which includes commit 2, which is already built.

Suggested pull request fixes the issue by getting last build information dependent on the branch.

### CODE REVIEW

**Comment by KostyaSha** [comment]
@ndeloof do you controlling target branches to what you are merging?

**Comment by ndeloof** [comment]
no I didn't noticed

**Comment by jglick** [comment]
@ndeloof better for @MarkEWaite to do the merging so he can keep track of what goes where. Was this cherry-picked to `master`?

**Comment by MarkEWaite** [comment]
This was not cherry picked to master. I haven't had time to resolve the @KostyaSha question trying to rationalize the several different variants of this fix.

**Comment by KostyaSha** [comment]
@jglick as i see @ndeloof just merged some number of PRs without investigating them all...

**Comment by ndeloof** [comment]
feel free to revert
@KostyaSha if your comments were more constructive I'll be happy to consider them, but now I just use my "_don't feed the troll_" filter.

**Comment by KostyaSha** [comment]
History from my viewpoint:
1) i hit polling exclusion issues and created test case.
2) later found many other PRs and linked to test case for references.
3) @MarkEWaite and @jglick reviewed/validated some PRs and said that fix is not really easy.
After month...
4) @ndeloof come from vacation and merged random PRs (because someone in maillist wanted his PR to be merged?)

@ndeloof if you will start reviewing PRs, you will probably provide some better design or fix, because i (still) believe in your dev experience in this top used plugin. For "constructive" i tried to group all related issues in https://github.com/jenkinsci/git-plugin/pull/277

**Pull request merged**
