### PR TITLE
[JENKINS-48061] Partial fix for the easy case of non-head revision in history of branch

### PR DESCRIPTION
**Pull request by stephenc**
See [JENKINS-48061](https://issues.jenkins-ci.org/browse/JENKINS-48061) 

Supercedes #557

This is only a partial fix, the two additional ignored test cases are required for the full fix

### CODE REVIEW

**Comment by stephenc** [comment]
May as well merge this half as it should help at least 80%

**Comment by mbelang** [comment]
@stephenc When do you plan the next release that will include that fix?

**Comment by MarkEWaite** [comment]
@mbelang have you confirmed that the [latest build](https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fgit-plugin/detail/master/193/artifacts) resolves the issue for you?  I didn't see any change in the cases I was testing.

**Comment by mbelang** [comment]
No I didn't. Are you saying that it is not really fix?

**Comment by MarkEWaite** [comment]
@stephenc said that it is 80%.  I would love to have you confirm that your failure case is included in that 80%.  That would indicate that there is some flaw in my testing (and give further confirmation that the change helps).

**Comment by mbelang** [comment]
I'll give it a try when I get a chance next week and get back to you.

**Comment by stephenc** [comment]
There are 3 tests in this PR, 2 of which are skipped because they represent cases that this partial fix does not address.

My guesstimate is that ~80% of people should match the first test case... but I have no evidence as to the actual %

**Comment by mbelang** [comment]
@stephenc Sorry for the delay but yeah our usecase fall under the ~80%. Your partial fix is good for us.

Thx

**Pull request merged**
