### PR TITLE
by default set the shallow clone checkbox

### PR DESCRIPTION
**Pull request by eduaranega**

### CODE REVIEW

**Comment by MarkEWaite** [comment]
I'll need to "test drive" this change.  

If this changes the behavior to always shallow clone, then the change will be rejected because there are too many workflows which depend on the ability to push from the Jenkins job to the origin repository.

**Comment by MarkEWaite** [comment]
I was wrong in my initial assessment that this would break compatibility.  This doesn't break compatibility as I'd originally feared.  It does change the default setting in the "Advanced clone options" section of the plugin.  That's the same place where the clone timeout is set, and where the path to the reference repository is set.  Unless advanced clone options are added to the job definition, the clone remains a "full-depth" (non-shallow) clone

As of git 1.9, [shallow clones can push changes](http://stackoverflow.com/questions/6941889/is-git-clone-depth-1-shallow-clone-more-useful-than-it-makes-out/21217267#21217267) to the origin repository.  That is encouraging, but we have many users still running git 1.7 variants (and some earlier thanks due to CentOS 5.11 / Red Hat 5.11, CentOS 6 / Red Hat 6) and others running git 1.7 and 1.8 variants (older Ubuntu and Debian releases).

I don't think we should default to a working copy which git versions prior to 1.9 can't use to push.   There are many use cases where users push from the working copy in the Jenkins job back to the origin repository.

I recommend against this change.

@ndeloof, does that seem reasonable to you, or should we include the change of default and gain the benefit of using less disc space for workspaces?

**Comment by ndeloof** [comment]
This change indeed could only be accepted if we only do support git 1.9 and later, which is not (yet) the case. I'm fine we make this a requirement for future release (as long as this is documented) - what's the available version on common linux LTS distributions ?

**Comment by MarkEWaite** [comment]
Git versions I've detected in various versions are captured in a [git client plugin test](https://github.com/jenkinsci/git-client-plugin/blob/master/src/test/java/org/jenkinsci/plugins/gitclient/CliGitAPIImplTest.java#L79).

Some examples:

| Operating System | Git version |
| :---------------------: | :------------: |
| Red Hat Linux 6.5  | 1.7.1         |
| OpenSUSE 13       | 1.8.4.5      |
| Debian 6                | 1.7.?         |
| Debian 7                |  1.7.10.4   |

**Comment by MarkEWaite** [comment]
Considering the age of the git implementations on many major Linux versions, I'm closing this pull request rather than have it linger for another 2-3 years until the major versions have reached git 1.9.  We still have users successfully running Red Hat 5 with limited use models, and this would break their limited use models.

**Pull request closed without merging**
